/**
 * CARC (Claim Adjustment Reason Code) and RARC reference.
 *
 * Ships as ONE searchable tool page over this dataset, not as hundreds of
 * thin per-code pages. Billers look these up constantly, which makes it a
 * genuine link-earning asset rather than a keyword play.
 */

export type DenialCategory =
  | "Eligibility"
  | "Authorization"
  | "Coding"
  | "Bundling"
  | "Contractual"
  | "Coverage"
  | "Timely filing"
  | "Patient responsibility"
  | "Data quality";

export type DenialCode = {
  code: string;
  group: "CARC" | "RARC";
  category: DenialCategory;
  /** The official-style short description. */
  title: string;
  /** What it actually means, in plain English. */
  meaning: string;
  /** What to do about this specific denial. */
  fix: string;
  /** How to stop it recurring. */
  prevent: string;
  /** True where the balance may not be billed to the patient. */
  writeOff?: boolean;
};

export const denialCodes: DenialCode[] = [
  { code: "CO-4", group: "CARC", category: "Coding", title: "Procedure code inconsistent with the modifier used, or a required modifier is missing", meaning: "The payer expected a modifier that was not submitted, or the modifier submitted contradicts the procedure code.", fix: "Identify the modifier the procedure requires for this payer, correct the claim line and resubmit as a corrected claim.", prevent: "Build payer-specific modifier requirements into claim scrubbing so missing modifiers are caught before submission." },
  { code: "CO-6", group: "CARC", category: "Coding", title: "Procedure or revenue code inconsistent with the patient's age", meaning: "The code billed is age-restricted and the patient's date of birth falls outside the permitted range.", fix: "Verify the patient's date of birth on file, then confirm the code is age-appropriate. Correct whichever is wrong and resubmit.", prevent: "Validate demographics at registration and apply age-edit checks during scrubbing." },
  { code: "CO-11", group: "CARC", category: "Coding", title: "The diagnosis is inconsistent with the procedure", meaning: "The diagnosis code submitted does not support medical necessity for the procedure under the payer's policy.", fix: "Review documentation for a diagnosis that accurately reflects the encounter and supports the service. Resubmit with correct linkage — never change a diagnosis to obtain payment.", prevent: "Check the payer's coverage policy for the procedure before service, and confirm diagnosis-to-procedure linkage during coding." },
  { code: "CO-15", group: "CARC", category: "Authorization", title: "The authorization number is missing, invalid, or does not apply", meaning: "An authorization exists or was required, but the number on the claim is absent or does not match the payer's record.", fix: "Retrieve the correct authorization number and confirm it covers this date of service, provider and procedure, then resubmit.", prevent: "Store authorization numbers against the specific service and date, and carry them onto the claim automatically." },
  { code: "CO-16", group: "CARC", category: "Data quality", title: "Claim or service lacks information needed for adjudication", meaning: "The single most common denial. A required data element is missing or invalid. Always paired with a RARC that names the specific field.", fix: "Read the accompanying RARC — CO-16 alone tells you nothing. The RARC identifies the missing element. Correct that field and resubmit.", prevent: "Track which RARCs accompany your CO-16 denials. They almost always cluster around a few repeatable registration or claim-build gaps." },
  { code: "CO-18", group: "CARC", category: "Data quality", title: "Exact duplicate claim or service", meaning: "The payer has already received an identical claim. Often triggered by resubmitting rather than filing a corrected claim.", fix: "Check the status of the original claim first. If it was legitimately a distinct service on the same day, resubmit with an appropriate modifier such as 76 or 91.", prevent: "Use corrected-claim workflows rather than resubmission, and confirm original claim status before refiling." },
  { code: "CO-22", group: "CARC", category: "Eligibility", title: "This care may be covered by another payer per coordination of benefits", meaning: "The patient has other coverage the payer believes is primary.", fix: "Confirm the correct payer order with the patient, bill the primary payer first, then submit to this payer with the primary's explanation of benefits.", prevent: "Capture and verify all active coverage at registration, including secondary and tertiary, and re-verify periodically." },
  { code: "CO-23", group: "CARC", category: "Contractual", title: "The impact of prior payer adjudication", meaning: "An adjustment reflecting what the primary payer already paid or adjusted. Usually informational rather than a true denial.", fix: "Verify the secondary payer applied the primary's payment correctly. If the math is right, no action is needed.", prevent: "Submit complete primary EOB data with secondary claims so adjudication is accurate first time.", writeOff: true },
  { code: "CO-24", group: "CARC", category: "Coverage", title: "Charges are covered under a capitation agreement or managed care plan", meaning: "The service falls under a capitated arrangement, so no fee-for-service payment is due.", fix: "Confirm the patient is genuinely enrolled in the capitated plan. If so, the balance is not separately billable.", prevent: "Flag capitated patients in your system so these services are not billed fee-for-service.", writeOff: true },
  { code: "CO-27", group: "CARC", category: "Eligibility", title: "Expenses incurred after coverage terminated", meaning: "The patient's coverage ended before the date of service.", fix: "Verify the actual termination date. If the patient has new coverage, bill that payer; if not, the balance transfers to patient responsibility.", prevent: "Verify eligibility before every visit rather than at intake only. Coverage terminations are invisible until you check." },
  { code: "CO-29", group: "CARC", category: "Timely filing", title: "The time limit for filing has expired", meaning: "The claim was submitted after the payer's filing deadline, typically 90 to 365 days from date of service.", fix: "Appeal only if you can document timely original submission — a clearinghouse acceptance report is the strongest evidence. Otherwise the revenue is lost.", prevent: "Work AR by filing deadline proximity, not just by balance. This denial is permanent and entirely preventable.", writeOff: true },
  { code: "CO-31", group: "CARC", category: "Eligibility", title: "Patient cannot be identified as our insured", meaning: "The payer cannot match the patient to an active policy using the identifiers submitted.", fix: "Re-verify the member ID, name spelling and date of birth exactly as they appear on the card, then resubmit.", prevent: "Scan or photograph insurance cards at registration and verify electronically rather than transcribing by hand." },
  { code: "CO-45", group: "CARC", category: "Contractual", title: "Charge exceeds the fee schedule or contracted maximum allowable", meaning: "Not a denial — this is the contractual adjustment between your billed charge and your contracted rate. The most frequently seen code on any remittance.", fix: "No action if the allowed amount matches your contract. If it is lower than contracted, this is an underpayment worth disputing.", prevent: "Load contracted rates into your system and reconcile allowed amounts against them. Underpayments hide inside routine CO-45 adjustments.", writeOff: true },
  { code: "CO-50", group: "CARC", category: "Coverage", title: "Non-covered service because it is not deemed a medical necessity", meaning: "The payer determined the service was not medically necessary under its coverage policy for the diagnosis submitted.", fix: "Appeal with clinical documentation addressing the payer's specific medical necessity criteria. Review the applicable coverage policy before writing the appeal.", prevent: "Check coverage policies before performing elective services, and issue an advance beneficiary notice where non-coverage is likely." },
  { code: "CO-58", group: "CARC", category: "Coverage", title: "Treatment was deemed to have been rendered in an inappropriate or invalid place of service", meaning: "The place of service code does not match where the payer believes the service should be performed.", fix: "Verify the place of service code is correct for where care was actually delivered, and correct if miscoded.", prevent: "Validate place of service codes during scrubbing, particularly for telehealth and off-campus locations where conventions change." },
  { code: "CO-59", group: "CARC", category: "Bundling", title: "Processed based on multiple or concurrent procedure rules", meaning: "Multiple procedure payment reduction was applied — subsequent procedures in the same session pay at a reduced rate.", fix: "Confirm the reduction matches the payer's published methodology. If procedures were genuinely distinct sessions, appeal with documentation.", prevent: "Model expected multiple-procedure reductions so reduced payment is not mistaken for underpayment.", writeOff: true },
  { code: "CO-96", group: "CARC", category: "Coverage", title: "Non-covered charges", meaning: "The service is not covered under the plan. A RARC normally explains why.", fix: "Read the accompanying RARC. If exclusion is correct and a valid advance notice was issued, bill the patient; otherwise it is a write-off.", prevent: "Verify benefits for the specific service, not just active coverage, and issue advance notices where exclusion is likely." },
  { code: "CO-97", group: "CARC", category: "Bundling", title: "The benefit for this service is included in the payment for another service already adjudicated", meaning: "The service was bundled into another procedure — typically an NCCI edit or a global period inclusion.", fix: "Determine whether the services were genuinely separate. If so, appeal with documentation supporting an appropriate modifier such as 25, 59 or an X modifier. If bundling is correct, adjust.", prevent: "Run NCCI edits during scrubbing and apply global period logic so bundled services are not billed separately." },
  { code: "CO-109", group: "CARC", category: "Eligibility", title: "Claim is not covered by this payer or contractor", meaning: "The claim went to the wrong payer entirely — a frequent cause is behavioral health carve-outs and Medicare Advantage plans billed as traditional Medicare.", fix: "Identify the correct payer and payer ID, then submit there. Watch the filing deadline, which runs from date of service.", prevent: "Verify the actual administering payer at eligibility check, including any carve-out arrangements." },
  { code: "CO-119", group: "CARC", category: "Coverage", title: "Benefit maximum for this time period or occurrence has been reached", meaning: "The patient has exhausted a covered benefit limit — visit caps, dollar maximums or frequency limits.", fix: "Confirm the maximum with the payer. Once genuinely exhausted, the balance becomes patient responsibility if properly noticed.", prevent: "Track remaining benefits for capped services such as therapy, chiropractic and behavioral health, and notify patients before the cap is hit." },
  { code: "CO-140", group: "CARC", category: "Data quality", title: "Patient or insured health identification number and name do not match", meaning: "The member ID and patient name submitted do not correspond in the payer's records.", fix: "Verify the member ID and the name exactly as shown on the insurance card, including suffixes and hyphenation, and resubmit.", prevent: "Use electronic eligibility verification, which returns the payer's own spelling, rather than manual card transcription." },
  { code: "CO-151", group: "CARC", category: "Coverage", title: "Payment adjusted because the payer deems the information submitted does not support this many services", meaning: "The units or frequency billed exceed what the payer considers supported for this service.", fix: "Verify units were calculated correctly. If the volume was clinically warranted, appeal with documentation justifying the quantity.", prevent: "Apply payer frequency and unit limits during scrubbing, particularly for timed codes, drug units and diagnostic studies." },
  { code: "CO-167", group: "CARC", category: "Coverage", title: "This diagnosis is not covered", meaning: "The diagnosis submitted is excluded from coverage under the plan.", fix: "Confirm the diagnosis accurately reflects documentation. If another supported diagnosis better represents the encounter, correct and resubmit.", prevent: "Review payer coverage policies for diagnosis restrictions before performing elective services." },
  { code: "CO-170", group: "CARC", category: "Coverage", title: "Payment denied when performed or billed by this type of provider", meaning: "The provider type or specialty is not eligible to bill this service under the plan.", fix: "Verify the rendering provider's enrollment and specialty designation with the payer. Correct the provider on the claim if it was submitted under the wrong NPI.", prevent: "Confirm scope-of-service eligibility during credentialing, not after the first denial." },
  { code: "CO-181", group: "CARC", category: "Coding", title: "Procedure code was invalid on the date of service", meaning: "The code was deleted, replaced or not yet effective on the service date. Common each January and October when code sets update.", fix: "Look up the valid code for that date of service and resubmit. Codes are date-of-service specific, not submission-date specific.", prevent: "Update code sets before each effective date and validate codes against the service date during scrubbing." },
  { code: "CO-197", group: "CARC", category: "Authorization", title: "Precertification, authorization or notification absent", meaning: "Required authorization was not obtained before the service was delivered.", fix: "Request retroactive authorization immediately — many payers permit it within a limited window. Otherwise appeal with clinical documentation supporting medical necessity.", prevent: "Verify authorization requirements at scheduling, not at check-in. Authorization denials arrive after the cost of care is already sunk." },
  { code: "CO-198", group: "CARC", category: "Authorization", title: "Precertification, authorization or notification exceeded", meaning: "Services were delivered beyond the number, duration or scope authorized.", fix: "Request an authorization extension with documentation supporting continued medical necessity, and appeal the delivered visits.", prevent: "Track remaining authorized units per patient and request extensions before exhaustion rather than after." },
  { code: "CO-204", group: "CARC", category: "Coverage", title: "Service, equipment or drug is not covered under the patient's current benefit plan", meaning: "A plan-level exclusion rather than a medical necessity determination.", fix: "Confirm the exclusion. If a valid advance notice was issued, the balance is billable to the patient; otherwise it is a write-off.", prevent: "Verify benefits for the specific service before delivery, and issue advance notices for likely exclusions." },
  { code: "CO-234", group: "CARC", category: "Bundling", title: "This procedure is not paid separately", meaning: "The service has no separate payment because its value is included in another service.", fix: "Verify the bundling is correct under the payer's policy. If the service was genuinely distinct, appeal with supporting documentation.", prevent: "Identify status-B and bundled codes during scrubbing so they are not billed with an expectation of payment.", writeOff: true },
  { code: "CO-236", group: "CARC", category: "Bundling", title: "This procedure or combination is not compatible with another procedure provided on the same day", meaning: "An NCCI procedure-to-procedure edit rejected the code pair.", fix: "Check the NCCI edit and whether it permits a modifier override. If services were genuinely distinct by site, session or encounter, resubmit with the appropriate X modifier and documentation.", prevent: "Run NCCI procedure-to-procedure edits during scrubbing rather than discovering pairs at adjudication." },
  { code: "PR-1", group: "CARC", category: "Patient responsibility", title: "Deductible amount", meaning: "The amount applied to the patient's annual deductible. Billable to the patient.", fix: "Bill the patient. Confirm the deductible was applied correctly against their accumulated year-to-date amount.", prevent: "Check real-time deductible status at eligibility verification so patients can be given accurate estimates and collected at the point of service." },
  { code: "PR-2", group: "CARC", category: "Patient responsibility", title: "Coinsurance amount", meaning: "The percentage of the allowed amount the patient owes. Billable to the patient.", fix: "Bill the patient, or the secondary payer if one exists.", prevent: "Quote coinsurance at the point of service using verified benefits so the balance is not a surprise." },
  { code: "PR-3", group: "CARC", category: "Patient responsibility", title: "Copayment amount", meaning: "The flat per-visit amount owed by the patient. Should generally be collected at the visit.", fix: "Bill the patient if it was not collected at check-in.", prevent: "Verify copay amounts at eligibility check and collect at the front desk. Copays collected later cost far more to recover." },
  { code: "PR-49", group: "CARC", category: "Coverage", title: "Routine or preventive examination not covered", meaning: "A routine service was billed to a plan that excludes it — common where preventive and problem-focused services are miscoded.", fix: "Confirm whether the visit was genuinely preventive. If a problem was addressed, it may be billable separately with appropriate coding.", prevent: "Distinguish preventive from problem-focused services during coding, and apply modifier 25 correctly when both occur." },
  { code: "PR-204", group: "CARC", category: "Patient responsibility", title: "Service not covered under the patient's plan, patient responsibility", meaning: "A non-covered service where the payer assigns the balance to the patient.", fix: "Bill the patient, provided a valid advance notice was issued before service.", prevent: "Issue advance beneficiary notices before delivering likely non-covered services. Without one, this balance is often not collectible." },
  { code: "PR-B7", group: "CARC", category: "Authorization", title: "Provider was not certified or eligible to be paid for this procedure on this date of service", meaning: "A credentialing gap — the rendering provider was not enrolled with the payer on the service date.", fix: "Check enrollment effective dates. If enrollment was later made retroactive, resubmit. If not, the revenue is generally unrecoverable.", prevent: "Begin credentialing well before a provider's start date and do not schedule payer-specific patients until enrollment is effective." },
  { code: "CO-B15", group: "CARC", category: "Bundling", title: "This service requires that a qualifying service or procedure be received and covered", meaning: "An add-on code was billed without its required primary procedure, or the primary was denied.", fix: "Confirm the primary procedure was billed and paid. If it was omitted, submit it; if denied, resolve the primary denial first.", prevent: "Enforce add-on-to-primary code pairing during scrubbing so add-on codes never submit alone." },
  { code: "N130", group: "RARC", category: "Coverage", title: "Consult plan benefit documents for information about restrictions on this service", meaning: "A remark code directing you to the plan's specific coverage terms. Accompanies a CARC rather than standing alone.", fix: "Review the plan's coverage policy for the service, then determine whether appeal is viable.", prevent: "Maintain payer policy references for high-volume services so restrictions are known before delivery." },
  { code: "N657", group: "RARC", category: "Coding", title: "This should be billed with the appropriate code for these services", meaning: "The payer is indicating a different code should have been used for what was performed.", fix: "Review documentation and identify the correct code, then submit a corrected claim.", prevent: "Track which services generate this remark; it usually signals a systematic coding misunderstanding rather than a one-off error." },
  { code: "MA130", group: "RARC", category: "Data quality", title: "Claim contains incomplete or invalid information; no appeal rights are afforded", meaning: "The claim was rejected rather than denied, so there is nothing to appeal. It must be corrected and refiled.", fix: "Correct the identified information and submit as a new claim, not an appeal. Watch the filing deadline, which continues running.", prevent: "Strengthen pre-submission scrubbing. Rejections carry no appeal rights, which makes prevention the only remedy." },
];

export const denialCategories: DenialCategory[] = [
  "Eligibility", "Authorization", "Coding", "Bundling",
  "Contractual", "Coverage", "Timely filing", "Patient responsibility", "Data quality",
];

export const getDenialCode = (code: string) =>
  denialCodes.find((d) => d.code.toLowerCase() === code.toLowerCase());
