/**
 * Long-form detail for the highest-demand denial codes.
 *
 * The dataset in `denial-codes.ts` ships as one searchable tool page and that
 * remains the primary asset. This file adds genuine depth — a worked example,
 * cross-references and an FAQ block — for the subset of codes that carry real
 * search demand, so those get their own route at /denial-codes/[code].
 *
 * Deliberately NOT all 190. A page per code across the whole dataset would
 * publish ~105 words of unique content each, which is the same thin profile as
 * the state pages Google crawled and declined to index. Only codes with enough
 * substance to stand alone belong here. `generateStaticParams` reads this file,
 * not `denialCodes`, so adding a page means writing the content first.
 */

export type DenialCodeDetail = {
  code: string;
  /**
   * Compact plain-English label for the page title.
   *
   * The official `title` in denial-codes.ts runs to 95 characters, so it
   * cannot drive a title, and without this the title was "CO-97 Denial Code
   * | Vizora" at 26 characters — matching the bare code query and nothing
   * else. Keep under 40 characters so the rendered title lands near 55.
   */
  shortLabel: string;
  /** A concrete scenario showing the denial arising and being resolved. */
  example: string[];
  /** Additional depth beyond the meaning/fix/prevent triple. */
  context: string[];
  /** Other codes commonly seen alongside or confused with this one. */
  relatedCodes: string[];
  /** Glossary slugs. */
  relatedTerms: string[];
  /** Service slugs. */
  relatedServices: string[];
  faqs: { question: string; answer: string }[];
};

export const denialCodeDetails: DenialCodeDetail[] = [
  {
    code: "CO-97",
    shortLabel: "Bundled Into Another Service",
    example: [
      "A patient attends for a scheduled lesion excision. The physician also performs a brief evaluation before the procedure and the practice bills an office visit alongside the excision. The remittance returns CO-97 against the office visit line.",
      "The question to answer is whether the evaluation was genuinely separate from the pre-service work the excision already includes. Every procedure carries an inherent evaluation component — assessing the site, confirming the plan, obtaining consent — and that work is inside the procedure's value.",
      "If the note shows only that assessment, the bundling is correct and the line adjusts. If the patient was separately evaluated for an unrelated complaint, the E/M is billable with modifier 25 and the appeal should attach the note showing the separate history, examination and decision-making.",
    ],
    context: [
      "CO-97 is generated by two distinct mechanisms that require different responses. The first is an NCCI procedure-to-procedure edit, where two codes billed together are considered one service. The second is global period inclusion, where a service falls inside the 10 or 90-day window following a surgical procedure.",
      "Distinguishing them matters because the fix differs. An NCCI edit may be overridden with an appropriate modifier where the services were genuinely distinct. A global period inclusion generally requires a different modifier entirely — 24 for an unrelated E/M during the postoperative period, or 79 for an unrelated procedure.",
      "Applying modifier 59 reflexively to clear CO-97 is the error that turns a recoverable denial into an audit finding. The X modifiers — XE, XS, XP, XU — are more specific and are preferred where they apply, because each states why the services were distinct rather than merely asserting that they were.",
    ],
    relatedCodes: ["CO-59", "CO-B15", "CO-4"],
    relatedTerms: ["ncci-edits", "modifier", "denial"],
    relatedServices: ["denial-management", "medical-coding", "claims-management"],
    faqs: [
      { question: "Can CO-97 be appealed?", answer: "Yes, when the services were genuinely separate. The appeal has to attach documentation supporting the distinction — a separate site, a separate session, or a separately identifiable evaluation — and the appropriate modifier. Where the bundling reflects a correctly applied NCCI edit or global period inclusion, there is nothing to appeal and the line adjusts." },
      { question: "What is the difference between CO-97 and CO-B15?", answer: "CO-97 means the service was bundled into another already adjudicated. CO-B15 means a required qualifying service was not billed or not paid — the payer expected a prerequisite procedure it did not receive. CO-97 asks whether the services were separate; CO-B15 asks whether something is missing." },
      { question: "Which modifier clears a CO-97 denial?", answer: "It depends on why it fired. For an NCCI edit with genuinely distinct services, modifier 59 or the more specific X modifiers — XE, XS, XP, XU. For a significant, separately identifiable E/M on the day of a procedure, modifier 25. For an unrelated service inside a global period, modifier 24 or 79. Using 59 reflexively is a common audit finding." },
      { question: "Is CO-97 billable to the patient?", answer: "No. The CO prefix indicates a contractual obligation, which means the provider absorbs the adjustment under the payer agreement. The balance cannot be transferred to the patient." },
    ],
  },
  {
    code: "CO-45",
    shortLabel: "A Contractual Adjustment",
    example: [
      "A practice bills $340 for an office visit. The remittance shows an allowed amount of $118, with $222 adjusted under CO-45. Nothing was denied — the payer paid its contracted rate and wrote off the difference between the charge and the contract.",
      "This is the most frequently occurring code on any remittance and it usually requires no action. The exception is the one worth building a process around: if the contracted rate for that code is $131 and the payer allowed $118, the difference is an underpayment hiding inside a routine adjustment.",
      "Because CO-45 appears on nearly every line of nearly every remittance, underpayments in this form are close to invisible without a systematic comparison of allowed amounts against loaded contract rates.",
    ],
    context: [
      "CO-45 is not a denial and treating it as one wastes effort. It is the mechanical expression of the difference between what a practice charges and what it agreed to accept, and that gap exists by design in every contracted relationship.",
      "The practical significance is what it conceals. Payers periodically load incorrect fee schedules, apply the wrong contract year, or process a claim against a different product's rates. Each produces a CO-45 that looks entirely ordinary on the remittance and is materially wrong.",
      "Detecting it requires contracted rates loaded in the practice management system and an automated comparison at payment posting. A practice that cannot state its contracted rate for a given code and payer cannot know whether it was paid correctly, and in that state every CO-45 is accepted on trust.",
    ],
    relatedCodes: ["CO-59", "CO-23", "CO-97"],
    relatedTerms: ["allowed-amount", "contractual-adjustment", "underpayment"],
    relatedServices: ["practice-analytics", "ar-management", "denial-management"],
    faqs: [
      { question: "Is CO-45 a denial?", answer: "No. It is the contractual adjustment between the billed charge and the contracted allowable — the routine difference that exists in every payer agreement. It appears on nearly every remittance line and normally requires no action." },
      { question: "Should CO-45 ever be disputed?", answer: "Yes, when the allowed amount is below the contracted rate. That is an underpayment presented in the form of a routine adjustment, and it is invisible without comparing allowed amounts against loaded contract rates at payment posting." },
      { question: "Can a CO-45 balance be billed to the patient?", answer: "No. The CO prefix means contractual obligation. Billing the patient for a contractual adjustment is balance billing and generally breaches the payer agreement." },
      { question: "Why is the CO-45 amount so large?", answer: "Because practices typically set charges well above contracted rates, often as a percentage of a benchmark. A large adjustment simply reflects the gap between the charge master and the contract, and says nothing about whether payment was correct." },
    ],
  },
  {
    code: "CO-16",
    shortLabel: "Read the Paired RARC",
    example: [
      "A batch of claims returns CO-16. The code itself identifies nothing — it means only that something required for adjudication is absent or invalid. The information is in the accompanying remark code.",
      "In this batch the paired RARC is N290, indicating a missing or invalid rendering provider identifier. Every affected claim came from one newly credentialed physician whose NPI was never added to the billing system's provider record.",
      "Correcting the provider record and refiling clears the whole batch. Working the denials individually without reading the RARC would have produced twenty separate investigations of the same single cause.",
    ],
    context: [
      "CO-16 is the most common denial code in circulation and the least informative on its own. It always travels with at least one remark code, and the remark code is where the actual defect is named.",
      "The operational failure it exposes is a workflow that routes denials by CARC alone. A queue of CO-16 denials is not a category of problem — it is an unsorted mixture of missing NPIs, invalid diagnosis pointers, absent referring provider data and malformed dates, each requiring different handling.",
      "Practices that track which RARCs accompany their CO-16 volume almost always find the denials cluster around a small number of repeatable registration or claim-build gaps. That analysis converts the highest-volume denial code on the remittance into a short list of fixable process defects.",
    ],
    relatedCodes: ["CO-140", "CO-31", "CO-18"],
    relatedTerms: ["carc", "rarc", "claim-scrubbing"],
    relatedServices: ["claims-management", "denial-management", "credentialing"],
    faqs: [
      { question: "What does CO-16 actually mean?", answer: "That the claim lacks information needed for adjudication. On its own it identifies nothing — it always accompanies a remark code that names the specific missing or invalid element. Reading the RARC is the entire first step." },
      { question: "Why is CO-16 so common?", answer: "Because it covers every category of missing or invalid data rather than one specific defect. A CO-16 queue is an unsorted mixture of different problems, which is why routing denials by CARC alone produces repeated investigation of the same underlying cause." },
      { question: "How do you prevent CO-16 denials?", answer: "Track which RARCs accompany them. The volume almost always clusters around a few repeatable registration or claim-build gaps — a missing rendering provider NPI, absent referring provider data, invalid diagnosis pointers. Fixing those at source clears the category rather than the claim." },
      { question: "Can a CO-16 claim simply be resubmitted?", answer: "Not as an identical resubmission, which produces CO-18 as a duplicate. Correct the element named by the remark code and file a corrected claim." },
    ],
  },
  {
    code: "CO-50",
    shortLabel: "Not Medically Necessary",
    example: [
      "An MRI of the lumbar spine is performed on an order reading \"low back pain\". The claim returns CO-50 — not medically necessary. The payer's coverage policy requires documented conservative therapy over a defined period, or specific neurological findings, before advanced imaging of the lumbar spine is covered.",
      "The service was clinically reasonable and is nonetheless unpayable, because the diagnosis submitted does not appear in the policy's covered indication list.",
      "An appeal succeeds only if the ordering physician's records contain what the policy requires and it was simply not conveyed on the claim. If conservative therapy was never documented, there is nothing to appeal — and changing the diagnosis to one that is covered, without documentation supporting it, is a false claim rather than a correction.",
    ],
    context: [
      "CO-50 is a coverage policy determination, not a clinical judgement about the service. Payers publish Local Coverage Determinations and commercial medical policies stating which diagnoses support which services, and adjudication compares the claim against that list mechanically.",
      "This makes CO-50 unusually predictable. The policies are published before the service, which means the denial is knowable at scheduling rather than discoverable at adjudication — and for elective services, that is the entire opportunity.",
      "For Medicare patients, an Advance Beneficiary Notice issued before the service transfers financial responsibility to the patient when the denial arrives. It must identify the specific service, the specific reason denial is expected, and an estimated cost, and be signed with an option selected. A routine ABN signed by every patient at registration is not valid.",
    ],
    relatedCodes: ["CO-96", "CO-151", "CO-167"],
    relatedTerms: ["medical-necessity", "appeal", "prior-authorization"],
    relatedServices: ["denial-management", "eligibility-verification", "medical-coding"],
    faqs: [
      { question: "How do you appeal a CO-50 denial?", answer: "By addressing the payer's specific coverage criteria rather than arguing general clinical appropriateness. Read the applicable Local Coverage Determination or medical policy first, then submit the documentation it names. An appeal that asserts the service was reasonable, without engaging the policy, fails." },
      { question: "Can a CO-50 balance be billed to the patient?", answer: "For Medicare, only if a valid Advance Beneficiary Notice was signed before the service, identifying that specific service and the expected reason for denial. Without one, the balance is written off. Commercial plans vary and the member agreement governs." },
      { question: "What is the difference between CO-50 and CO-96?", answer: "CO-50 means the service is not covered because it was not deemed medically necessary for the diagnosis submitted. CO-96 means the service is non-covered under the plan generally — an exclusion rather than a necessity determination. CO-96 normally carries a remark code explaining which exclusion applies." },
      { question: "How do you prevent CO-50?", answer: "Screen the diagnosis on the order against the payer's published coverage policy before the service is performed, while there is still time to query the ordering physician. For elective services this converts an unrecoverable denial into a conversation." },
    ],
  },
  {
    code: "CO-29",
    shortLabel: "Timely Filing Limit Expired",
    example: [
      "A claim for a service performed fourteen months earlier is submitted after being discovered in an unworked queue. It returns CO-29 — the filing deadline has expired. The payer's limit was twelve months from the date of service.",
      "There is no clinical or coding defect. The service was provided, documented and correctly coded. The revenue is lost because of elapsed time alone.",
      "The only appeal that succeeds is one demonstrating the claim was originally filed within the deadline. A clearinghouse acceptance report showing the original submission date is the strongest evidence available; a note in the practice management system that someone believes it was sent is not.",
    ],
    context: [
      "Timely filing is the most permanent denial category in revenue cycle management. Almost every other denial has a path to payment through correction or appeal. This one generally does not, which makes prevention the only meaningful control.",
      "Deadlines vary widely — commonly ninety days to a year from the date of service, and shorter for some commercial plans and some secondary filings. They also run from different starting points depending on payer and claim type, which is why a single internal deadline applied to all payers reliably misses some.",
      "The operational implication is that accounts receivable should be worked by proximity to filing deadline, not only by balance. A large claim with six months remaining is less urgent than a small one with three weeks, and a queue sorted by dollar value inverts that priority.",
    ],
    relatedCodes: ["CO-109", "CO-18", "CO-22"],
    relatedTerms: ["timely-filing", "days-in-ar", "appeal"],
    relatedServices: ["ar-management", "claims-management", "denial-management"],
    faqs: [
      { question: "Can a timely filing denial be appealed?", answer: "Only with proof of timely original submission. A clearinghouse acceptance report showing the original date is the strongest evidence. Without documentary proof the claim reached the payer inside the window, the revenue is lost." },
      { question: "What are typical timely filing deadlines?", answer: "Commonly ninety days to a year from the date of service, varying by payer, plan and claim type. Secondary claims often run from the primary payer's remittance date rather than the service date. Applying one internal deadline across all payers reliably misses the shorter ones." },
      { question: "Can a timely filing balance be billed to the patient?", answer: "No. The CO prefix makes it a contractual obligation, and the failure was administrative rather than the patient's. Billing it to the patient generally breaches the payer agreement." },
      { question: "How do you prevent CO-29?", answer: "Work accounts receivable by filing deadline proximity rather than by balance, and load each payer's actual deadline rather than a single internal default. This denial is entirely preventable and entirely permanent, which is an unusual and costly combination." },
    ],
  },
  {
    code: "PR-204",
    shortLabel: "Not Covered by the Plan",
    example: [
      "A patient receives a service and the remittance returns PR-204 — not covered under the patient's current benefit plan. The PR prefix means the balance is patient responsibility rather than a provider write-off.",
      "Before transferring it, the first check is whether the service is genuinely excluded or whether the wrong plan was billed. Patients frequently hold more than one coverage, and a service excluded under one plan may be covered under another.",
      "Where the exclusion is real, the balance is billable — but a patient who was not told beforehand receives an unexpected bill, which is the most common source of collection disputes and the reason benefit verification matters more than eligibility verification alone.",
    ],
    context: [
      "PR-204 turns on the distinction between eligibility and benefits, which are commonly conflated. Confirming a patient has active coverage says nothing about whether this particular service is covered under their specific plan.",
      "Plan-level exclusions are the cause here: cosmetic procedures, some dental and vision services, experimental treatments, and services outside the plan's defined benefit set. The patient is covered; the service is not.",
      "Because the balance is patient responsibility, the practice's exposure is a collection problem rather than a write-off. Setting expectation before the service — a documented conversation, an estimate, a signed acknowledgement — converts a disputed bill into an anticipated one, and is far cheaper than pursuing the balance afterwards.",
    ],
    relatedCodes: ["CO-96", "PR-1", "PR-3"],
    relatedTerms: ["patient-responsibility", "eligibility-verification", "out-of-network"],
    relatedServices: ["eligibility-verification", "patient-collections", "patient-support"],
    faqs: [
      { question: "Is PR-204 billable to the patient?", answer: "Yes. The PR prefix designates patient responsibility, so the balance transfers rather than being written off. Confirm first that the correct plan was billed — patients often hold more than one coverage, and a service excluded under one may be covered under another." },
      { question: "What is the difference between PR-204 and CO-96?", answer: "Both indicate a non-covered service, but the prefix determines who bears the cost. PR-204 makes it patient responsibility. CO-96 makes it a contractual obligation the provider absorbs. The prefix, not the description, decides whether a bill can be sent." },
      { question: "How do you prevent PR-204 surprises?", answer: "Verify benefits for the specific service rather than only confirming active coverage. Eligibility tells you the patient is insured; benefits tell you whether this service is covered under their plan. Communicating the expected cost before the service converts a disputed bill into an anticipated one." },
      { question: "Does an ABN apply to PR-204?", answer: "An ABN is a Medicare instrument. For commercial plans, the equivalent is a documented financial responsibility acknowledgement signed before the service. Either way the point is the same — the patient has to know before, not after." },
    ],
  },
  {
    code: "CO-15",
    shortLabel: "Authorization Missing or Invalid",
    example: [
      "A procedure requiring prior authorisation is performed and the authorisation number is entered on the claim. It returns CO-15 — the authorisation number is missing, invalid, or does not apply.",
      "The number was real. It was obtained for the same patient and the same procedure, but for a date three weeks earlier that was rescheduled. The authorisation's valid date range had expired by the time the procedure took place.",
      "This is the dominant form of CO-15: not a missing authorisation, but one that does not match what was actually performed — wrong date range, wrong procedure code, wrong site of service, or wrong rendering provider.",
    ],
    context: [
      "Authorisation is granted against a specific set of facts, and any of them changing invalidates it. The approval covers named procedure codes, a named provider, a named facility and a defined date window. A claim that departs from any of those is unauthorised even though an authorisation exists.",
      "The failure this exposes is storing authorisations against the patient rather than against the service. A record showing this patient has an authorisation cannot answer whether it covers this date, this code and this provider — which is the question adjudication actually asks.",
      "Rescheduling deserves particular attention because it silently breaks authorisations that were correct when obtained. A confirmation step that re-checks the authorisation window whenever an appointment moves prevents most of this category.",
    ],
    relatedCodes: ["CO-197", "CO-50", "CO-109"],
    relatedTerms: ["prior-authorization", "denial", "eligibility-verification"],
    relatedServices: ["prior-authorization", "denial-management", "eligibility-verification"],
    faqs: [
      { question: "Why does CO-15 appear when an authorisation was obtained?", answer: "Because the authorisation does not match what was billed. Approvals are granted against specific procedure codes, a specific provider and facility, and a defined date window. A rescheduled appointment falling outside the original window is unauthorised even though an authorisation exists." },
      { question: "Can CO-15 be appealed?", answer: "Yes where a valid authorisation covering the actual service exists and was simply not carried onto the claim. Submit the authorisation number, approved codes and date range as evidence. Where no authorisation covering the service was obtained, most payers will not grant one retroactively." },
      { question: "How do you prevent CO-15?", answer: "Store authorisations against the specific codes, provider, facility and date range approved rather than against the patient, and re-verify the window whenever an appointment is rescheduled. Rescheduling silently invalidates authorisations that were correct when obtained." },
      { question: "Is CO-15 billable to the patient?", answer: "Generally not. The CO prefix makes it a contractual obligation, and failure to obtain or convey authorisation is an administrative failure rather than a patient one." },
    ],
  },
  {
    code: "CO-197",
    shortLabel: "Precertification Absent",
    example: [
      "An advanced imaging study is performed on a referral marked urgent. The claim returns CO-197 — precertification, authorisation or notification absent.",
      "The referring practice believed it had initiated authorisation; the imaging centre assumed the referring practice had completed it. Neither confirmed, and the study went ahead on the strength of an assumption.",
      "The service was clinically appropriate, was performed competently, and is unpayable. Retroactive authorisation is granted by some payers in narrow circumstances, usually involving genuine emergency, but is not generally available for elective imaging.",
    ],
    context: [
      "CO-197 differs from CO-15 in a way that matters operationally. CO-15 means an authorisation exists but does not match; CO-197 means none was obtained at all. The first is often recoverable, the second frequently is not.",
      "Authorisation issues are the third-largest denial category industry-wide at 12.8% according to Optum's analysis of 124 million claim remits, and they concentrate in services where responsibility is split between an ordering practice and a performing one — imaging, surgery, infusion, durable medical equipment.",
      "The structural fix is to stop treating authorisation as the referring party's responsibility. Whoever bills the claim bears the loss, which means whoever bills should verify that authorisation is actually on file rather than assumed, at the point the service is scheduled.",
    ],
    relatedCodes: ["CO-15", "CO-50", "CO-96"],
    relatedTerms: ["prior-authorization", "denial", "appeal"],
    relatedServices: ["prior-authorization", "eligibility-verification", "denial-management"],
    faqs: [
      { question: "What is the difference between CO-197 and CO-15?", answer: "CO-197 means no authorisation was obtained at all. CO-15 means one exists but does not match the claim — wrong dates, codes, provider or facility. CO-15 is frequently recoverable by supplying the correct details; CO-197 usually is not, because payers rarely grant authorisation retroactively." },
      { question: "Can authorisation be obtained retroactively?", answer: "Some payers allow it in narrow circumstances, most commonly genuine emergencies or cases where eligibility was not knowable at the time. It is not generally available for elective services, and relying on it as a fallback is not a workable process." },
      { question: "Who is responsible for obtaining authorisation?", answer: "Nominally the ordering practice, but the party that bills the claim bears the financial loss when it was not obtained. That asymmetry is why the performing practice should confirm authorisation is on file rather than assume the referring party completed it." },
      { question: "How common are authorisation denials?", answer: "Optum's analysis of 124 million claim remits puts authorisation issues at 12.8% of denials, the third-largest category. They concentrate in services where responsibility is split between an ordering and a performing practice." },
    ],
  },
  {
    code: "CO-4",
    shortLabel: "Modifier Missing or Inconsistent",
    example: [
      "A bilateral procedure is billed without a modifier indicating both sides were treated. The claim returns CO-4 — the procedure code is inconsistent with the modifier used, or a required modifier is missing.",
      "The payer's edit expected either modifier 50 or separate lines with LT and RT. Receiving neither, it could not determine what was performed and rejected the line rather than assuming.",
      "Correcting the modifier and filing a corrected claim resolves it. The recurring version of this denial is a charge template that omits a modifier the payer requires for a specific code, which produces the same denial on every instance until someone traces the pattern rather than fixing claims individually.",
    ],
    context: [
      "CO-4 covers two distinct situations: a required modifier is absent, or a modifier is present that contradicts the code. Both are claim-build defects rather than clinical ones, which makes them fully preventable through scrubbing.",
      "Modifier requirements are payer-specific in ways that resist generalisation. A code requiring no modifier for one payer may require one for another, and the requirement changes when payers revise their edits — usually at the start of a plan year, without individual notice.",
      "Because the defect is mechanical, this denial category responds well to pattern analysis. Grouping CO-4 denials by procedure code and payer almost always reveals a small number of code-payer combinations producing most of the volume, each fixable once in the scrubber rather than repeatedly on claims.",
    ],
    relatedCodes: ["CO-97", "CO-11", "CO-16"],
    relatedTerms: ["modifier", "claim-scrubbing", "cpt-code"],
    relatedServices: ["medical-coding", "claims-management", "denial-management"],
    faqs: [
      { question: "What causes a CO-4 denial?", answer: "Either a modifier the procedure code requires was not submitted, or a modifier was submitted that contradicts the code. Both are claim-build defects rather than clinical ones, which means they are preventable in scrubbing rather than correctable only after adjudication." },
      { question: "Why do modifier requirements differ between payers?", answer: "Because each payer maintains its own edits. A code needing no modifier for one payer may require one for another, and requirements are revised periodically — usually at the start of a plan year and usually without individual notice." },
      { question: "How do you stop CO-4 recurring?", answer: "Group the denials by procedure code and payer. A small number of code-payer combinations normally produce most of the volume, and each is fixable once in the claim scrubber rather than repeatedly on individual claims." },
      { question: "Can a CO-4 claim be resubmitted?", answer: "File a corrected claim with the right modifier rather than resubmitting the original, which would return CO-18 as a duplicate." },
    ],
  },
  {
    code: "CO-11",
    shortLabel: "Diagnosis Does Not Match",
    example: [
      "A diagnostic study is billed with a screening diagnosis. The claim returns CO-11 — the diagnosis is inconsistent with the procedure.",
      "The payer's policy lists which diagnoses support the procedure, and the one submitted is not among them. The service may have been entirely appropriate; the linkage on the claim does not establish it.",
      "The correct response is to review the documentation for a diagnosis that accurately reflects the encounter and supports the service, then resubmit with correct linkage. What is not acceptable is selecting a covered diagnosis because it will pay — that is not a coding correction, it is a false claim.",
    ],
    context: [
      "CO-11 is a linkage failure rather than a coverage failure. The diagnosis may be perfectly valid and the procedure perfectly appropriate, and the claim can still deny because the two were not connected in a way the payer's edits recognise.",
      "A frequent mechanical cause is diagnosis pointers. Where several diagnoses appear on a claim, each service line points to the ones supporting it, and a line pointing at the wrong diagnosis produces CO-11 even though the correct diagnosis is present on the claim.",
      "The distinction between CO-11 and CO-50 is worth holding clearly. CO-11 says the diagnosis submitted does not support this procedure. CO-50 says the service was not medically necessary under policy. They frequently arise from the same underlying situation but call for different responses — a coding review in the first case, a coverage policy review in the second.",
    ],
    relatedCodes: ["CO-50", "CO-16", "CO-167"],
    relatedTerms: ["icd-10-cm", "medical-necessity", "cpt-code"],
    relatedServices: ["medical-coding", "denial-management", "claims-management"],
    faqs: [
      { question: "What does CO-11 mean?", answer: "The diagnosis submitted does not support medical necessity for the procedure under the payer's policy. It is a linkage failure — the diagnosis may be valid and the procedure appropriate, and the claim still denies because the two were not connected in a way the payer's edits recognise." },
      { question: "Can the diagnosis be changed to get the claim paid?", answer: "Only if documentation supports the different diagnosis. Reviewing the record for a diagnosis that accurately reflects the encounter is a legitimate correction. Selecting a covered diagnosis because it will pay, without documentation supporting it, is a false claim." },
      { question: "What is the difference between CO-11 and CO-50?", answer: "CO-11 says the diagnosis does not support this procedure — a coding and linkage question. CO-50 says the service was not medically necessary under the payer's coverage policy. They often arise from the same situation but call for different responses: a coding review versus a coverage policy review." },
      { question: "Why does CO-11 appear when the right diagnosis is on the claim?", answer: "Usually diagnosis pointers. Each service line points to the diagnoses supporting it, and a line pointing at the wrong one produces CO-11 even though the correct diagnosis appears elsewhere on the claim." },
    ],
  },
  {
    code: "CO-18",
    shortLabel: "Exact Duplicate Claim",
    example: [
      "A claim is not paid after several weeks, so it is submitted again. The second submission returns CO-18 — exact duplicate claim or service.",
      "The original claim was in process, not lost. Resubmitting created a duplicate rather than prompting action, and the duplicate now has to be resolved before the original can be worked.",
      "The other common cause is legitimate: two genuinely distinct services on the same day that look identical on a claim. A repeat chest radiograph, a second identical laboratory test, bilateral procedures billed on separate lines. These need a modifier — 76, 77, 91 or an anatomic modifier — to adjudicate as the separate services they are.",
    ],
    context: [
      "CO-18 divides cleanly into two causes with opposite fixes. One is a workflow problem — resubmitting instead of checking status or filing a corrected claim. The other is a coding problem — genuinely distinct same-day services without the modifier that distinguishes them.",
      "The workflow cause is worth addressing first because it is self-inflicted and creates work rather than revealing it. Checking claim status before refiling, and using corrected-claim workflows when something needs to change, eliminates the category.",
      "For the coding cause, the modifier has to match the reason for repetition. Modifier 76 covers a repeat procedure by the same physician, 77 a repeat by a different physician, and 91 a repeat clinical diagnostic laboratory test. Using a generic distinct-service modifier where a specific repeat modifier exists is weaker on audit.",
    ],
    relatedCodes: ["CO-16", "CO-29", "CO-97"],
    relatedTerms: ["modifier", "rejection", "claim-scrubbing"],
    relatedServices: ["claims-management", "denial-management", "ar-management"],
    faqs: [
      { question: "Why did a resubmitted claim return CO-18?", answer: "Because the original was still in process rather than lost. Resubmitting an identical claim creates a duplicate that then has to be resolved before the original can be worked. Check claim status before refiling, and use a corrected-claim workflow when something needs to change." },
      { question: "How do you bill two identical services on the same day?", answer: "With a modifier that explains the repetition — 76 for a repeat procedure by the same physician, 77 for a repeat by a different physician, 91 for a repeat clinical diagnostic laboratory test, or an anatomic modifier where the sites differ." },
      { question: "Is CO-18 appealable?", answer: "Where the services were genuinely distinct, yes — resubmit with the appropriate modifier and documentation showing both were performed. Where it is a true duplicate of a claim already in process, there is nothing to appeal; the original claim is what needs working." },
      { question: "How do you prevent CO-18?", answer: "Check original claim status before any refiling, use corrected-claim workflows rather than resubmission, and apply repeat modifiers during scrubbing where same-day duplicates are legitimate." },
    ],
  },
  {
    code: "CO-22",
    shortLabel: "Another Payer Is Primary",
    example: [
      "A claim returns CO-22 — this care may be covered by another payer per coordination of benefits. The patient holds coverage through their own employer and is also a dependent on a spouse's plan, and the claim went to the wrong one first.",
      "Coordination of benefits rules determine which plan pays first, and they are not a matter of patient preference. For dependent children, many plans apply the birthday rule — the plan of the parent whose birthday falls earlier in the calendar year is primary, regardless of which parent is older.",
      "The fix is to establish the correct order, bill the primary payer, and then submit to the secondary with the primary's explanation of benefits attached. Filing deadlines run throughout, so time spent determining the order is time consumed from the secondary's window.",
    ],
    context: [
      "CO-22 is an information failure at registration rather than a claim defect. The patient usually knows they have two coverages; nobody asked, or asked once at intake and never again.",
      "Coverage changes constantly — employment, marriage, a spouse's open enrolment, a child ageing off a plan, Medicare eligibility. Verifying only at first visit means the record is accurate on day one and progressively less so afterwards.",
      "Medicare secondary payer rules add a further layer, with defined circumstances in which Medicare is secondary to group health coverage. Those situations have their own questionnaire and their own documentation expectations, and getting the order wrong produces both a denial and a compliance exposure.",
    ],
    relatedCodes: ["CO-109", "CO-27", "CO-16"],
    relatedTerms: ["coordination-of-benefits", "eligibility-verification", "timely-filing"],
    relatedServices: ["eligibility-verification", "claims-management", "denial-management"],
    faqs: [
      { question: "What does CO-22 mean?", answer: "The payer believes another plan is primary for this care. It is a coordination of benefits issue rather than a coverage denial — the service may be perfectly covered, once billed to the correct payer in the correct order." },
      { question: "How is primary payer order determined?", answer: "By coordination of benefits rules, not patient preference. Employer coverage is typically primary over a spouse's plan for the employee. For dependent children many plans apply the birthday rule — the parent whose birthday falls earlier in the calendar year is primary, regardless of age." },
      { question: "How do you bill a secondary payer?", answer: "After the primary adjudicates, submit to the secondary with the primary's explanation of benefits attached. Secondary filing deadlines often run from the primary's remittance date rather than the date of service, so delays in resolving the order consume the secondary window." },
      { question: "How do you prevent CO-22?", answer: "Ask about all active coverage at every visit rather than only at intake. Coverage changes with employment, marriage, open enrolment and Medicare eligibility, so a record verified once is accurate on day one and progressively less so afterwards." },
    ],
  },
  {
    code: "CO-27",
    shortLabel: "Coverage Already Terminated",
    example: [
      "A patient attends for a follow-up visit. The claim returns CO-27 — expenses incurred after coverage terminated. Their employment ended six weeks earlier and the plan terminated at the end of that month.",
      "Eligibility had been verified, at the patient's first visit eight months previously. Nothing since. The patient did not mention the change, and from the practice's perspective nothing looked different.",
      "The balance transfers to the patient unless they have new coverage, and a patient who has just lost their job receiving an unexpected bill is both a collection problem and a difficult conversation that a thirty-second eligibility check would have prevented.",
    ],
    context: [
      "Coverage termination is invisible without checking. There is no notification to the practice, the insurance card remains in the patient's wallet and looks identical, and the patient frequently does not connect their employment change to their medical billing.",
      "Registration and eligibility errors are the single largest denial category industry-wide, at 21.9% in Optum's analysis of 124 million claim remits. Termination is a substantial share of that, and it is among the most mechanically preventable denials in existence.",
      "The control is verifying eligibility before every visit rather than at intake. Electronic verification takes seconds, returns the payer's own record rather than the patient's recollection, and catches terminations, plan changes and coverage that was never active in the first place.",
    ],
    relatedCodes: ["CO-22", "CO-31", "CO-109"],
    relatedTerms: ["eligibility-verification", "patient-responsibility", "denial"],
    relatedServices: ["eligibility-verification", "patient-collections", "denial-management"],
    faqs: [
      { question: "Can a CO-27 balance be billed to the patient?", answer: "Generally yes, since there is no coverage to absorb it. Check first whether the patient obtained new coverage responsible for the date of service, and whether any continuation coverage applies retroactively." },
      { question: "Why was coverage active at the last visit but not now?", answer: "Because termination is invisible without checking. No notification reaches the practice, the insurance card looks identical, and patients frequently do not connect an employment change to their medical billing. Only verification against the payer's record surfaces it." },
      { question: "How do you prevent CO-27?", answer: "Verify eligibility before every visit rather than at intake only. Electronic verification takes seconds and returns the payer's current record. Registration and eligibility errors are the largest denial category industry-wide at 21.9%, and termination is a substantial share of it." },
      { question: "What if the patient has retroactive coverage?", answer: "Some coverage, including continuation coverage and certain Medicaid determinations, is granted retroactively. Where that applies, rebill the correct payer — but watch the filing deadline, which usually runs from the date of service rather than the coverage determination." },
    ],
  },
  {
    code: "CO-31",
    shortLabel: "Patient Not Found as Insured",
    example: [
      "A claim returns CO-31 — the patient cannot be identified as our insured. The member ID was transcribed by hand from a photograph of an insurance card and one character was read incorrectly.",
      "Nothing about the coverage was wrong. The patient is insured, the plan is active, and the service is covered. The claim simply did not match a record on the payer's system.",
      "Re-verifying the member ID, name spelling and date of birth exactly as the payer holds them, then resubmitting, resolves it. The systematic fix is electronic eligibility verification, which returns the payer's own spelling rather than asking a person to read a card correctly.",
    ],
    context: [
      "CO-31 is a matching failure. The payer is not saying the patient has no coverage — it is saying it cannot find them using the identifiers provided.",
      "The most common causes are mechanical: a transposed digit in the member ID, a name entered as it is spoken rather than as the plan holds it, a hyphenated surname entered in one form on the card and another in the payer's system, a date of birth off by a digit, or a dependent billed under their own name where the plan is held in the subscriber's.",
      "Manual transcription is the root cause of most of it, and electronic verification is the fix because it eliminates the transcription step entirely — the payer returns its own record, which is by definition the spelling that will match at adjudication.",
    ],
    relatedCodes: ["CO-140", "CO-16", "CO-27"],
    relatedTerms: ["eligibility-verification", "claim-scrubbing", "rejection"],
    relatedServices: ["eligibility-verification", "claims-management", "denial-management"],
    faqs: [
      { question: "Does CO-31 mean the patient has no insurance?", answer: "No. It means the payer cannot match the patient to a policy using the identifiers submitted. The coverage is often perfectly active — the claim simply did not match a record, usually because of a transcription error in the member ID, name or date of birth." },
      { question: "What causes CO-31 most often?", answer: "Manual transcription. A transposed digit in the member ID, a name entered as spoken rather than as the plan holds it, a hyphenated surname recorded differently, or a dependent billed under their own name where the policy is in the subscriber's." },
      { question: "How do you fix a CO-31 denial?", answer: "Re-verify the member ID, name spelling and date of birth exactly as they appear in the payer's record — not as they appear on the card, which may itself differ — then file a corrected claim." },
      { question: "How do you prevent CO-31?", answer: "Use electronic eligibility verification rather than manual card transcription. It returns the payer's own spelling, which is by definition the version that will match at adjudication." },
    ],
  },
  {
    code: "CO-59",
    shortLabel: "Multiple Procedure Reduction",
    example: [
      "Three procedures are performed in one session. The remittance shows full payment on the first, and reduced payment on the second and third under CO-59 — processed based on multiple or concurrent procedure rules.",
      "This is not a denial. Payers apply a published multiple procedure payment reduction on the basis that certain overheads — preparation, positioning, access — are not duplicated when procedures are performed together.",
      "The check worth running is whether the reduction matches the payer's stated methodology and whether the ranking was correct. Reductions are applied in descending order of value, so a procedure ranked incorrectly produces a larger total reduction than the rules require.",
    ],
    context: [
      "CO-59 is frequently mistaken for underpayment because the received amount is lower than the fee schedule suggests. It is not — it is the fee schedule applied through a reduction rule that was known in advance.",
      "The reduction percentages and the services they apply to are published. Surgical procedures, diagnostic imaging and therapy services each have their own methodology, and imaging in particular has separate reductions for the professional and technical components.",
      "Modelling expected reductions is what separates real underpayments from correctly applied rules. A practice that does not model them either writes off genuine underpayments as normal reductions, or spends effort disputing reductions that were correct.",
    ],
    relatedCodes: ["CO-97", "CO-45", "CO-B15"],
    relatedTerms: ["allowed-amount", "underpayment", "modifier"],
    relatedServices: ["practice-analytics", "denial-management", "ar-management"],
    faqs: [
      { question: "Is CO-59 a denial?", answer: "No. It is a multiple procedure payment reduction — subsequent procedures in the same session pay at a reduced rate on the basis that preparation and access overheads are not duplicated. The reduction is published in advance and applied mechanically." },
      { question: "Should a CO-59 reduction be disputed?", answer: "Only where the reduction does not match the payer's published methodology, or where the procedures were performed in genuinely separate sessions. Ranking matters too — reductions apply in descending order of value, so an incorrectly ranked procedure produces a larger total reduction than the rules require." },
      { question: "How do you tell a CO-59 reduction from an underpayment?", answer: "By modelling the expected reduction against the payer's published methodology. Without that model, genuine underpayments get written off as normal reductions and correct reductions get disputed — both expensive in different ways." },
      { question: "Is a CO-59 amount billable to the patient?", answer: "No. It is a contractual obligation under the CO prefix and cannot be transferred to the patient." },
    ],
  },
  {
    code: "CO-96",
    shortLabel: "Non-Covered Charges",
    example: [
      "A claim returns CO-96 — non-covered charges — accompanied by a remark code identifying the specific exclusion. Reading the remark code is the whole first step; CO-96 alone does not say why.",
      "In this case the remark identifies a service excluded from the plan's benefit set. The exclusion is genuine and the service was performed knowing coverage was uncertain.",
      "For a Medicare patient, whether the balance is billable turns entirely on whether a valid Advance Beneficiary Notice was signed before the service. With one, the balance transfers. Without one, it is written off — and the notice cannot be obtained after the fact.",
    ],
    context: [
      "CO-96 and CO-50 are frequently confused. CO-50 is a medical necessity determination — the service might be covered for a different diagnosis. CO-96 is an exclusion — the service is not covered under this plan regardless of the clinical picture.",
      "That distinction changes what an appeal can achieve. A necessity denial can be appealed with clinical documentation addressing the coverage criteria. An exclusion cannot be appealed on clinical grounds at all, because coverage was never available.",
      "The prefix also matters more than the description here. CO-96 places the cost with the provider as a contractual obligation. The same non-covered situation carrying a PR prefix places it with the patient. Reading the prefix before deciding whether to bill is what prevents improper balance billing.",
    ],
    relatedCodes: ["CO-50", "PR-204", "CO-167"],
    relatedTerms: ["medical-necessity", "patient-responsibility", "appeal"],
    relatedServices: ["denial-management", "eligibility-verification", "patient-collections"],
    faqs: [
      { question: "What is the difference between CO-96 and CO-50?", answer: "CO-50 is a medical necessity determination — the service might be covered for a different diagnosis, so a clinical appeal is possible. CO-96 is an exclusion: the service is not covered under the plan regardless of the clinical picture, so there is nothing to appeal on clinical grounds." },
      { question: "Can a CO-96 balance be billed to the patient?", answer: "For Medicare, only with a valid Advance Beneficiary Notice signed before the service, naming that service and the expected reason for denial. Without one it is written off, and the notice cannot be obtained retroactively. The CO prefix otherwise makes it a provider obligation." },
      { question: "Why does CO-96 need a remark code to interpret?", answer: "Because CO-96 states only that charges are non-covered, not which exclusion applies. The accompanying remark code names the specific reason, and that determines whether anything can be done." },
      { question: "How do you prevent CO-96?", answer: "Verify benefits for the specific service rather than only confirming active coverage, and issue an advance notice where exclusion is likely. Eligibility confirms the patient is insured; benefits confirm whether this service is covered." },
    ],
  },
  {
    code: "CO-109",
    shortLabel: "Wrong Payer or Contractor",
    example: [
      "A claim for a behavioural health visit is submitted to the patient's medical plan and returns CO-109 — not covered by this payer or contractor. The plan carves behavioural health out to a separate managed behavioural health organisation with its own payer ID.",
      "The patient's card shows the medical plan's name and logo, and often shows the carve-out administrator only in small print on the reverse, if at all.",
      "The claim has to be resubmitted to the correct entity, and the filing deadline has been running from the date of service throughout. A claim that spends two months at the wrong payer arrives at the right one with two months less runway.",
    ],
    context: [
      "CO-109 means the claim reached an entity with no responsibility for it. The three dominant causes are behavioural health carve-outs, Medicare Advantage plans billed as traditional Medicare, and Medicaid managed care plans billed to the state.",
      "The Medicare Advantage case is particularly costly because it is easy to miss. A patient with a Medicare Advantage plan is not covered by traditional Medicare at all, and claims sent there deny — but the patient will often describe themselves simply as having Medicare.",
      "The prevention is verifying the actual administering entity at eligibility check rather than reading the card. Electronic verification returns which payer is genuinely responsible, including carve-outs and managed care assignments that the card does not disclose.",
    ],
    relatedCodes: ["CO-22", "CO-27", "CO-29"],
    relatedTerms: ["eligibility-verification", "timely-filing", "coordination-of-benefits"],
    relatedServices: ["eligibility-verification", "claims-management", "denial-management"],
    faqs: [
      { question: "What causes CO-109?", answer: "The claim went to an entity with no responsibility for it. The three dominant causes are behavioural health carved out to a separate administrator, Medicare Advantage plans billed as traditional Medicare, and Medicaid managed care plans billed to the state rather than the assigned plan." },
      { question: "Why does the insurance card not show the right payer?", answer: "Because carve-out arrangements frequently are not disclosed on the card, or appear only in small print on the reverse. The card shows the plan the patient recognises, not necessarily the entity that adjudicates a given service type." },
      { question: "Does CO-109 affect the filing deadline?", answer: "Yes, and this is the expensive part. The deadline runs from the date of service throughout, so time spent at the wrong payer is consumed from the correct payer's window. Resubmit promptly rather than treating it as routine rework." },
      { question: "How do you prevent CO-109?", answer: "Verify the actual administering entity at eligibility check rather than reading the card. Electronic verification returns which payer is genuinely responsible, including carve-outs and managed care assignments the card does not disclose." },
    ],
  },
  {
    code: "CO-119",
    shortLabel: "Benefit Maximum Reached",
    example: [
      "A physical therapy claim returns CO-119 — the benefit maximum for this time period or occurrence has been reached. The plan covers a defined number of therapy visits per year and the patient has used them.",
      "The visits were clinically indicated and were provided. The plan's obligation simply ended, and no appeal changes that.",
      "The failure is not billing; it is that nobody was counting. A patient midway through a course of therapy should know before the cap that they are approaching it, and should be given the choice of continuing at their own cost rather than discovering it afterwards.",
    ],
    context: [
      "Benefit maximums apply most often to therapy, chiropractic, behavioural health and certain durable medical equipment — service lines characterised by repeated visits over a course of treatment.",
      "Two details cause most avoidable losses. Caps are frequently counted per plan year rather than per course of treatment, so a patient crossing a plan year mid-course gets a fresh allowance while one starting late in the year has less than the headline number suggests. And visits used at another provider count toward the same cap, invisibly.",
      "Because the limit is knowable from the eligibility response for most payers, tracking remaining benefits at the point of scheduling is achievable. Practices that do it convert a denial into a financial conversation held at the right time.",
    ],
    relatedCodes: ["PR-204", "CO-96", "CO-151"],
    relatedTerms: ["eligibility-verification", "patient-responsibility", "denial"],
    relatedServices: ["eligibility-verification", "patient-collections", "practice-analytics"],
    faqs: [
      { question: "Can CO-119 be appealed?", answer: "Rarely with success. The plan applied its own stated benefit limit correctly, so there is no error to overturn. Some plans allow an exception request on medical necessity grounds for continued care, which is a different process from an appeal." },
      { question: "Is a CO-119 balance billable to the patient?", answer: "Generally yes once the benefit is genuinely exhausted, provided the patient was properly notified. The practical difficulty is that a patient who was not told beforehand receives an unexpected bill, which is the most common source of collection disputes in capped service lines." },
      { question: "How are benefit maximums counted?", answer: "Usually per plan year rather than per course of treatment, and visits used at other providers count toward the same cap. A patient starting a course late in the plan year has less than the headline number available, and may not know it." },
      { question: "How do you prevent CO-119?", answer: "Track remaining benefits for capped services at scheduling — therapy, chiropractic, behavioural health and some durable medical equipment. The limit is available in the eligibility response for most payers, which makes this a counting problem rather than an information problem." },
    ],
  },
  {
    code: "CO-151",
    shortLabel: "Units Not Supported",
    example: [
      "A claim returns CO-151 — the payer determines the information submitted does not support this many or this frequency of services. A series of visits was billed over a short period and the payer considers the volume unsupported by the documentation.",
      "This is not the same as a frequency limit expressed as a benefit maximum. It is an assessment that the documentation does not justify the quantity billed.",
      "An appeal has to address quantity specifically — why this many services were required for this patient over this period. Documentation supporting each individual service does not by itself answer a question about the total.",
    ],
    context: [
      "CO-151 arises most often in service lines where quantity is a clinical judgement rather than a fixed protocol: therapy, behavioural health, chronic care management, and time-based services generally.",
      "The documentation gap it exposes is a specific one. Notes typically justify each encounter well and rarely articulate the treatment plan's arc — the expected duration, the intended frequency, the measurable goal, and the progress toward it. That arc is what makes quantity defensible.",
      "A plan of care stating expected frequency and duration, with periodic progress notes measuring against stated goals, converts an appeal about volume from an assertion into evidence. It also tends to improve care, which is the more important reason to do it.",
    ],
    relatedCodes: ["CO-119", "CO-50", "CO-167"],
    relatedTerms: ["medical-necessity", "appeal", "denial"],
    relatedServices: ["denial-management", "medical-coding", "practice-analytics"],
    faqs: [
      { question: "What does CO-151 mean?", answer: "The payer judges that the documentation does not support the quantity or frequency of services billed. It is distinct from a benefit maximum — the issue is not that a limit was reached, but that the volume billed is not justified by the record." },
      { question: "How do you appeal CO-151?", answer: "By addressing quantity specifically — why this many services were required for this patient over this period. Documentation justifying each individual encounter does not answer a question about the total, which is what the denial actually asks." },
      { question: "Which services see CO-151 most?", answer: "Those where quantity is a clinical judgement rather than a fixed protocol: physical and occupational therapy, behavioural health, chronic care management, and time-based services generally." },
      { question: "How do you prevent CO-151?", answer: "Maintain a plan of care stating expected frequency, duration and measurable goals, with periodic progress notes measuring against them. That arc is what makes quantity defensible, and it is usually the element missing from notes that otherwise document each visit well." },
    ],
  },
  {
    code: "CO-167",
    shortLabel: "Diagnosis Not Covered",
    example: [
      "A claim returns CO-167 — this diagnosis is not covered. The plan excludes the condition itself, rather than questioning whether the service was appropriate for it.",
      "Diagnosis-level exclusions apply to a narrow set of situations: some cosmetic indications, certain work-related conditions that belong to workers compensation, and conditions specifically excluded by the plan document.",
      "The first check is whether the diagnosis is correct and complete. A claim carrying only an excluded diagnosis, where the record also supports a covered one that better reflects the encounter, is a coding problem rather than a coverage problem.",
    ],
    context: [
      "CO-167 sits between CO-11 and CO-50 and is distinct from both. CO-11 says the diagnosis does not support this procedure. CO-50 says the service was not medically necessary. CO-167 says the diagnosis itself is outside the plan's coverage entirely.",
      "Work-related conditions are the most common practical cause. A condition attributable to employment belongs to workers compensation, and a group health plan that identifies it as work-related will exclude it — sometimes before the workers compensation claim has been accepted, leaving the patient temporarily between two payers.",
      "Where the exclusion is correct, the route to payment is the correct payer rather than an appeal. Identifying that payer and its filing deadline early is what preserves the claim, because the deadline usually runs from the date of service regardless of how long the coverage question took to resolve.",
    ],
    relatedCodes: ["CO-11", "CO-50", "CO-96"],
    relatedTerms: ["icd-10-cm", "medical-necessity", "coordination-of-benefits"],
    relatedServices: ["denial-management", "medical-coding", "eligibility-verification"],
    faqs: [
      { question: "What does CO-167 mean?", answer: "The diagnosis itself is not covered under the plan. It differs from CO-11, which says the diagnosis does not support the procedure, and from CO-50, which says the service was not medically necessary. Here the condition is outside coverage entirely." },
      { question: "What causes CO-167 most often?", answer: "Work-related conditions that belong to workers compensation rather than group health, some cosmetic indications, and conditions specifically excluded by the plan document." },
      { question: "Can CO-167 be appealed?", answer: "Only where the diagnosis submitted was incorrect or incomplete and the record supports a covered diagnosis that better reflects the encounter. Where the exclusion is correctly applied, the route to payment is the correct payer rather than an appeal." },
      { question: "What happens with work-related conditions?", answer: "They belong to workers compensation, and a group health plan identifying them as work-related will exclude them — sometimes before the compensation claim is accepted, leaving the patient temporarily between payers. Identify the correct payer and its filing deadline early, since the deadline usually runs from the date of service." },
    ],
  },
  {
    code: "CO-B15",
    shortLabel: "Qualifying Service Not Billed",
    example: [
      "A claim returns CO-B15 — this service requires a qualifying service or procedure to have been received and covered. An add-on code was billed without the primary procedure it attaches to.",
      "Add-on codes are not independently billable by design. They describe additional work performed alongside a primary service, and their value assumes that primary service was performed and paid.",
      "The other common form is a service requiring a prerequisite — a therapeutic procedure requiring a prior diagnostic study, or a treatment requiring documented failure of a first-line therapy. In those cases the prerequisite must have been performed and, usually, covered.",
    ],
    context: [
      "CO-B15 differs from CO-97 in a way worth holding clearly. CO-97 says a service was bundled into another already paid — too much was billed. CO-B15 says a required companion service is absent — too little was billed, or the prerequisite was never performed.",
      "The add-on code case is usually a claim-build defect and is straightforwardly fixable: bill the primary and the add-on together, on the same claim, with the primary paid. Splitting them across claims produces this denial even when both were performed.",
      "The prerequisite case is not fixable after the fact. Where a payer requires a diagnostic study before a therapeutic procedure and the study was never done, the procedure is unpayable regardless of how appropriate it was. That requirement is published in medical policy and is knowable before scheduling.",
    ],
    relatedCodes: ["CO-97", "CO-59", "CO-16"],
    relatedTerms: ["ncci-edits", "cpt-code", "prior-authorization"],
    relatedServices: ["medical-coding", "denial-management", "claims-management"],
    faqs: [
      { question: "What is the difference between CO-B15 and CO-97?", answer: "CO-97 says the service was bundled into another already adjudicated — too much was billed. CO-B15 says a required qualifying service is missing — either it was not billed with this one, or it was never performed." },
      { question: "Why did an add-on code deny with CO-B15?", answer: "Because the primary procedure it attaches to was not billed, was billed on a separate claim, or was not paid. Add-on codes are not independently billable; bill the primary and add-on together on the same claim." },
      { question: "Can CO-B15 be appealed?", answer: "Where the qualifying service was performed and simply was not billed together, yes — refile correctly with both. Where the prerequisite was never performed, there is nothing to appeal; the requirement was a precondition, not a documentation question." },
      { question: "How do you prevent CO-B15?", answer: "Pair add-on codes with their primaries during scrubbing, and check payer medical policy for prerequisite requirements before scheduling procedures that have them — such as a diagnostic study required before a therapeutic one." },
    ],
  },
  {
    code: "PR-1",
    shortLabel: "Deductible Amount",
    example: [
      "A claim adjudicates with PR-1 — the amount applied to the patient's deductible. The plan is active, the service is covered, and nothing was denied. The patient simply has not yet met their annual deductible, so the allowed amount falls to them.",
      "The practice receives no payment from the payer on this claim and bills the patient for the allowed amount.",
      "The predictable difficulty is January, when deductibles reset. A patient accustomed to a small copayment suddenly owes the full allowed amount, and unless the practice checks deductible status and says so at check-in, that arrives as a surprise bill weeks later.",
    ],
    context: [
      "PR-1 is not a denial and should never be worked as one. It is correct adjudication of a covered service against the patient's benefit design, and the only revenue cycle question is collection.",
      "The volume of it has grown with high-deductible plan design, which has shifted a substantial share of revenue from payers to patients. Patient balances collect at materially lower rates than payer balances, and they get harder to collect the further they sit from the visit.",
      "Deductible status is available in the eligibility response, which makes point-of-service collection possible rather than aspirational. Practices that check the remaining deductible and collect at check-in convert the hardest balance in the revenue cycle into the easiest.",
    ],
    relatedCodes: ["PR-2", "PR-3", "PR-204"],
    relatedTerms: ["patient-responsibility", "allowed-amount", "eligibility-verification"],
    relatedServices: ["patient-collections", "eligibility-verification", "patient-support"],
    faqs: [
      { question: "Is PR-1 a denial?", answer: "No. It is the allowed amount applied to the patient's deductible on a covered service. The plan is working as designed — the patient has not yet met their annual deductible, so the balance falls to them rather than the payer." },
      { question: "Why do PR-1 balances spike in January?", answer: "Because deductibles reset at the start of the plan year. A patient used to paying a small copayment suddenly owes the full allowed amount, and unless deductible status is checked and explained at check-in, it arrives as a surprise bill weeks later." },
      { question: "How do you collect deductible balances effectively?", answer: "At the point of service. Deductible status is available in the eligibility response, so the remaining amount is knowable before the visit ends. Patient balances collect at materially lower rates the further they sit from the encounter." },
      { question: "What is the difference between PR-1, PR-2 and PR-3?", answer: "They identify which part of the patient's cost share applies. PR-1 is the deductible, PR-2 is coinsurance, and PR-3 is the copayment. All three are patient responsibility on covered services rather than denials." },
    ],
  },
  {
    code: "PR-2",
    shortLabel: "Coinsurance Amount",
    example: [
      "A claim adjudicates with PR-2 — coinsurance. The patient has met their deductible, so the plan now shares cost at the stated percentage, commonly eighty per cent payer and twenty per cent patient.",
      "The practice receives the payer's share and bills the patient for the coinsurance portion of the allowed amount — not of the billed charge, which is a distinction patients frequently misunderstand.",
      "Explaining that coinsurance applies to the contracted allowed amount rather than the practice's charge resolves most of the disputes this generates, and is easier said at check-in than in a collections call.",
    ],
    context: [
      "Coinsurance differs from a copayment in a way that matters for collection. A copayment is a fixed amount known before the visit. Coinsurance is a percentage of an allowed amount that is not finally determined until adjudication, so the exact figure cannot be stated with certainty in advance.",
      "It can be estimated closely, though, where contracted rates are loaded. An estimate given at check-in, framed as an estimate, is far better than silence — it sets expectation and enables collection of a deposit against the eventual balance.",
      "Out-of-network coinsurance is the version that produces genuine distress, because the percentage is applied to a larger base and the patient may additionally be responsible for the difference between the allowed amount and the charge. Identifying network status before the service is what prevents that conversation.",
    ],
    relatedCodes: ["PR-1", "PR-3", "PR-204"],
    relatedTerms: ["patient-responsibility", "allowed-amount", "out-of-network"],
    relatedServices: ["patient-collections", "eligibility-verification", "patient-support"],
    faqs: [
      { question: "What is the difference between coinsurance and a copayment?", answer: "A copayment is a fixed amount known before the visit. Coinsurance is a percentage of the allowed amount, which is not finally determined until adjudication — so the exact figure cannot be stated with certainty in advance, only estimated." },
      { question: "Is coinsurance calculated on the billed charge?", answer: "No, on the contracted allowed amount. This is one of the most common patient misunderstandings, and explaining it at check-in resolves most of the disputes it otherwise generates." },
      { question: "Can coinsurance be estimated before the visit?", answer: "Closely, where contracted rates are loaded in the system. An estimate offered as an estimate sets expectation and supports collecting a deposit, which is far better than saying nothing and billing later." },
      { question: "Why is out-of-network coinsurance so much higher?", answer: "Because the percentage applies to a larger base, and the patient may additionally owe the difference between the allowed amount and the full charge. Identifying network status before the service is what prevents that." },
    ],
  },
  {
    code: "PR-3",
    shortLabel: "Copayment Amount",
    example: [
      "A claim adjudicates with PR-3 — copayment. A fixed amount applies to the visit under the patient's plan, and the payer pays the balance of the allowed amount.",
      "Copayments are the most collectable balance in the revenue cycle because the amount is fixed, known in advance, and printed on the insurance card. They are also among the most frequently uncollected, because collecting at the desk requires a process rather than a system.",
      "A copayment not collected at the visit becomes a statement, then a follow-up, then in many cases a write-off — for an amount that was available at the front desk and would have taken thirty seconds.",
    ],
    context: [
      "PR-3 is not a denial and requires no revenue cycle work beyond collection. Its significance is entirely operational.",
      "The economics are stark. Producing and mailing a statement, then following up, frequently costs a meaningful fraction of a typical copayment. Collecting a modest amount at the desk is close to pure margin; collecting the same amount after three statements may be net negative.",
      "The card is not always current, which is the one caveat. Copayment amounts change at plan renewal and cards are not always reissued, so verifying the current copayment in the eligibility response rather than reading the card avoids collecting the wrong amount and refunding later.",
    ],
    relatedCodes: ["PR-1", "PR-2", "PR-204"],
    relatedTerms: ["patient-responsibility", "eligibility-verification", "payment-posting"],
    relatedServices: ["patient-collections", "eligibility-verification", "patient-support"],
    faqs: [
      { question: "Is PR-3 a denial?", answer: "No. It is the patient's fixed copayment on a covered service. It requires no revenue cycle work beyond collection — its significance is operational rather than a claims problem." },
      { question: "Why should copayments be collected at the visit?", answer: "Because the economics change sharply afterwards. Producing and mailing a statement, then following up, can cost a meaningful fraction of a typical copayment. Collected at the desk it is close to pure margin; collected after three statements it may be net negative." },
      { question: "Should the copayment on the insurance card be trusted?", answer: "Not entirely. Amounts change at plan renewal and cards are not always reissued. Verifying the current copayment in the eligibility response avoids collecting the wrong amount and having to refund." },
      { question: "What if the patient cannot pay at the visit?", answer: "Record the balance and offer a payment arrangement rather than waiving it silently. Routine waiver of cost-sharing raises compliance concerns under payer agreements and, for federal programmes, beyond them." },
    ],
  },
  {
    code: "CO-140",
    shortLabel: "Member ID and Name Do Not Match",
    example: [
      "A claim returns CO-140 — the patient or insured health identification number and name do not match. The member ID is correct and the name is not, or the reverse.",
      "A common cause is a dependent billed under their own name against a policy held in a subscriber's name, where the payer expects the subscriber's details in the insured fields and the patient's in the patient fields.",
      "Another is a name that changed — marriage, divorce, legal change — updated in the practice's record and not with the payer, or the reverse. Both records are internally consistent and they do not match each other.",
    ],
    context: [
      "CO-140 is closely related to CO-31 and the distinction is subtle. CO-31 means the payer cannot identify the patient at all. CO-140 means it found a record but the identifiers do not agree with what was submitted.",
      "The practical consequence is the same: verify against the payer's own record rather than against the card or the patient's account. Electronic eligibility returns the payer's spelling, which is what adjudication will match against.",
      "Where a name has genuinely changed, the patient has to update it with the payer. The practice cannot fix a mismatch by changing its own record to match the payer if the payer holds outdated information — that only relocates the discrepancy.",
    ],
    relatedCodes: ["CO-31", "CO-16", "CO-27"],
    relatedTerms: ["eligibility-verification", "claim-scrubbing", "rejection"],
    relatedServices: ["eligibility-verification", "claims-management", "denial-management"],
    faqs: [
      { question: "What is the difference between CO-140 and CO-31?", answer: "CO-31 means the payer cannot identify the patient at all using the identifiers submitted. CO-140 means it located a record but the name and member ID do not agree with what was sent. Both are resolved by verifying against the payer's own record." },
      { question: "Why do dependents trigger CO-140?", answer: "Because the policy is held in the subscriber's name. Payers generally expect the subscriber's details in the insured fields and the patient's in the patient fields, and billing a dependent's name in both produces a mismatch." },
      { question: "How do you fix a name mismatch?", answer: "Verify how the payer holds the name and submit that. Where the payer's record is genuinely outdated — after a marriage or legal name change — the patient has to update it with the payer; changing only the practice's record relocates the discrepancy rather than resolving it." },
      { question: "How do you prevent CO-140?", answer: "Use electronic eligibility verification, which returns the payer's own spelling of the name and the exact member ID format, rather than transcribing from a card." },
    ],
  },
];

/** Codes with a dedicated page. Everything else lives in the lookup tool. */
export const detailedCodes = denialCodeDetails.map((d) => d.code);

export const getDenialDetail = (code: string) =>
  denialCodeDetails.find((d) => d.code.toLowerCase() === code.toLowerCase());
