/**
 * State pages.
 *
 * Location pSEO is where thin content is most tempting and most punished — a
 * template with a swapped city name is a doorway page. Every state below
 * carries facts that are actually different state to state: the Medicaid
 * program's real name, the Medicare Administrative Contractor and jurisdiction
 * that adjudicates its Part B claims, and the regional payers that dominate
 * its commercial mix. Those three drive genuinely different billing behavior.
 *
 * Deliberately NOT included: specific prompt-pay statute day counts. Those
 * vary by state and by claim type, and publishing unverified numbers on a
 * compliance-adjacent site is worse than omitting them.
 */

export type StateInfo = {
  slug: string;
  name: string;
  abbr: string;
  /** Official Medicaid program name — differs meaningfully by state. */
  medicaid: string;
  /** Medicare Administrative Contractor handling Part B claims. */
  mac: string;
  /** MAC jurisdiction identifier. */
  jurisdiction: string;
  /** Regional commercial payers with meaningful share in this state. */
  payers: string[];
  /** Largest metros, used for internal copy and local relevance. */
  metros: string[];
  /** Medicaid expansion status — materially changes payer mix and self-pay volume. */
  expansion: boolean;
  /** How the state delivers Medicaid. Determines who actually adjudicates the claim. */
  medicaidModel: "managed-care" | "fee-for-service" | "mixed";
  /** One genuinely state-specific billing consideration. */
  note: string;
};

export const states: StateInfo[] = [
  { slug: "alabama", name: "Alabama", abbr: "AL", medicaid: "Alabama Medicaid", mac: "Palmetto GBA", jurisdiction: "JJ", payers: ["Blue Cross and Blue Shield of Alabama", "UnitedHealthcare", "Viva Health"], metros: ["Birmingham", "Montgomery", "Mobile", "Huntsville"], expansion: false, medicaidModel: "fee-for-service", note: "Alabama runs primary care case management rather than comprehensive risk-based managed care, so Medicaid claims are adjudicated by the state rather than by competing MCO plans." },
  { slug: "alaska", name: "Alaska", abbr: "AK", medicaid: "Alaska Medical Assistance", mac: "Noridian Healthcare Solutions", jurisdiction: "JF", payers: ["Premera Blue Cross Blue Shield of Alaska", "Aetna", "Moda Health"], metros: ["Anchorage", "Fairbanks", "Juneau"], expansion: true, medicaidModel: "fee-for-service", note: "Alaska's fee-for-service Medicaid and extreme geography make travel and telehealth billing rules unusually consequential for rural practices." },
  { slug: "arizona", name: "Arizona", abbr: "AZ", medicaid: "AHCCCS", mac: "Noridian Healthcare Solutions", jurisdiction: "JF", payers: ["Blue Cross Blue Shield of Arizona", "Banner Health Plans", "UnitedHealthcare"], metros: ["Phoenix", "Tucson", "Mesa", "Scottsdale"], expansion: true, medicaidModel: "managed-care", note: "AHCCCS was the last state Medicaid program to launch and has operated as a fully managed care model since inception, so plan-level rules matter more than state-level ones." },
  { slug: "arkansas", name: "Arkansas", abbr: "AR", medicaid: "ARHOME", mac: "Novitas Solutions", jurisdiction: "JH", payers: ["Arkansas Blue Cross and Blue Shield", "QualChoice", "Ambetter"], metros: ["Little Rock", "Fayetteville", "Fort Smith"], expansion: true, medicaidModel: "mixed", note: "Arkansas uses PASSE organizations for members with complex behavioral health and developmental needs, which sit outside standard Medicaid managed care billing." },
  { slug: "california", name: "California", abbr: "CA", medicaid: "Medi-Cal", mac: "Noridian Healthcare Solutions", jurisdiction: "JE", payers: ["Anthem Blue Cross", "Blue Shield of California", "Kaiser Permanente", "Health Net"], metros: ["Los Angeles", "San Diego", "San Francisco", "Sacramento", "San Jose"], expansion: true, medicaidModel: "managed-care", note: "Medi-Cal operates through roughly two dozen managed care plans whose authorization rules and encounter requirements differ by county, so 'billing Medi-Cal' is really billing whichever plan covers that county." },
  { slug: "colorado", name: "Colorado", abbr: "CO", medicaid: "Health First Colorado", mac: "Novitas Solutions", jurisdiction: "JH", payers: ["Anthem Blue Cross Blue Shield", "Kaiser Permanente", "Rocky Mountain Health Plans"], metros: ["Denver", "Colorado Springs", "Aurora", "Boulder"], expansion: true, medicaidModel: "mixed", note: "Colorado routes Medicaid through Regional Accountable Entities rather than conventional MCOs, which changes how behavioral health and care coordination are billed." },
  { slug: "connecticut", name: "Connecticut", abbr: "CT", medicaid: "HUSKY Health", mac: "National Government Services", jurisdiction: "JK", payers: ["Anthem Blue Cross Blue Shield", "ConnectiCare", "Cigna"], metros: ["Hartford", "New Haven", "Stamford", "Bridgeport"], expansion: true, medicaidModel: "fee-for-service", note: "Connecticut moved off managed care organizations entirely and administers Medicaid on a fee-for-service basis through a single administrative services organization — unusual among large states." },
  { slug: "delaware", name: "Delaware", abbr: "DE", medicaid: "Diamond State Health Plan", mac: "Novitas Solutions", jurisdiction: "JL", payers: ["Highmark Blue Cross Blue Shield Delaware", "AmeriHealth Caritas", "Aetna"], metros: ["Wilmington", "Dover", "Newark"], expansion: true, medicaidModel: "managed-care", note: "Delaware's small provider market means a handful of plans dominate, and Highmark's regional presence gives commercial contracting outsized influence on rates." },
  { slug: "florida", name: "Florida", abbr: "FL", medicaid: "Statewide Medicaid Managed Care", mac: "First Coast Service Options", jurisdiction: "JN", payers: ["Florida Blue", "Humana", "AvMed", "Sunshine Health"], metros: ["Miami", "Orlando", "Tampa", "Jacksonville"], expansion: false, medicaidModel: "managed-care", note: "Florida's Statewide Medicaid Managed Care program is organized into regions with different plan lineups, and its large Medicare Advantage penetration makes MA prior authorization a dominant workflow." },
  { slug: "georgia", name: "Georgia", abbr: "GA", medicaid: "Georgia Families", mac: "Palmetto GBA", jurisdiction: "JJ", payers: ["Anthem Blue Cross Blue Shield of Georgia", "Peach State Health Plan", "Kaiser Permanente"], metros: ["Atlanta", "Augusta", "Savannah", "Columbus"], expansion: false, medicaidModel: "managed-care", note: "Georgia has not expanded Medicaid, so practices carry a higher share of self-pay and sliding-scale patients than in neighbouring expansion states." },
  { slug: "hawaii", name: "Hawaii", abbr: "HI", medicaid: "Med-QUEST", mac: "Noridian Healthcare Solutions", jurisdiction: "JE", payers: ["HMSA (Blue Cross Blue Shield of Hawaii)", "Kaiser Permanente", "UHA Health Insurance"], metros: ["Honolulu", "Hilo", "Kailua-Kona"], expansion: true, medicaidModel: "managed-care", note: "HMSA holds a dominant commercial share in Hawaii, and the state's Prepaid Health Care Act produces employer coverage patterns found nowhere else in the country." },
  { slug: "idaho", name: "Idaho", abbr: "ID", medicaid: "Idaho Medicaid", mac: "Noridian Healthcare Solutions", jurisdiction: "JF", payers: ["Blue Cross of Idaho", "Regence BlueShield of Idaho", "PacificSource"], metros: ["Boise", "Idaho Falls", "Nampa"], expansion: true, medicaidModel: "mixed", note: "Idaho runs medical Medicaid largely fee-for-service while carving behavioral health and dual-eligible care into managed arrangements, so routing depends on service type." },
  { slug: "illinois", name: "Illinois", abbr: "IL", medicaid: "HealthChoice Illinois", mac: "National Government Services", jurisdiction: "J6", payers: ["Blue Cross and Blue Shield of Illinois", "Aetna Better Health", "Meridian"], metros: ["Chicago", "Aurora", "Rockford", "Naperville"], expansion: true, medicaidModel: "managed-care", note: "HealthChoice Illinois consolidated to a smaller set of statewide plans, but Cook County's provider density means commercial contracting varies sharply between Chicago and downstate." },
  { slug: "indiana", name: "Indiana", abbr: "IN", medicaid: "Healthy Indiana Plan", mac: "Wisconsin Physicians Service", jurisdiction: "J8", payers: ["Anthem Blue Cross Blue Shield", "CareSource", "MDwise"], metros: ["Indianapolis", "Fort Wayne", "Evansville"], expansion: true, medicaidModel: "managed-care", note: "The Healthy Indiana Plan uses POWER account cost-sharing, which creates patient-responsibility mechanics that differ from standard Medicaid." },
  { slug: "iowa", name: "Iowa", abbr: "IA", medicaid: "IA Health Link", mac: "Wisconsin Physicians Service", jurisdiction: "J5", payers: ["Wellmark Blue Cross and Blue Shield", "Amerigroup Iowa", "Molina Healthcare"], metros: ["Des Moines", "Cedar Rapids", "Davenport"], expansion: true, medicaidModel: "managed-care", note: "Iowa's fully privatized Medicaid managed care has seen repeated plan turnover, making enrollment verification before each visit more important than in stable markets." },
  { slug: "kansas", name: "Kansas", abbr: "KS", medicaid: "KanCare", mac: "Wisconsin Physicians Service", jurisdiction: "J5", payers: ["Blue Cross and Blue Shield of Kansas", "Aetna Better Health", "Sunflower Health Plan"], metros: ["Wichita", "Overland Park", "Kansas City", "Topeka"], expansion: false, medicaidModel: "managed-care", note: "KanCare covers the entire Medicaid population through three plans, and Kansas has not expanded eligibility — raising self-pay exposure for practices near the Missouri line." },
  { slug: "kentucky", name: "Kentucky", abbr: "KY", medicaid: "Kentucky Medicaid", mac: "CGS Administrators", jurisdiction: "J15", payers: ["Anthem Blue Cross Blue Shield", "Passport Health Plan", "WellCare"], metros: ["Louisville", "Lexington", "Bowling Green"], expansion: true, medicaidModel: "managed-care", note: "Kentucky's Medicaid expansion produced one of the largest coverage shifts in the country, and managed care plans handle the bulk of the adult population." },
  { slug: "louisiana", name: "Louisiana", abbr: "LA", medicaid: "Healthy Louisiana", mac: "Novitas Solutions", jurisdiction: "JH", payers: ["Blue Cross and Blue Shield of Louisiana", "Healthy Blue", "Aetna Better Health"], metros: ["New Orleans", "Baton Rouge", "Shreveport", "Lafayette"], expansion: true, medicaidModel: "managed-care", note: "Healthy Louisiana operates through a small set of plans, and the state's high rate of chronic disease burden makes chronic care management billing materially valuable." },
  { slug: "maine", name: "Maine", abbr: "ME", medicaid: "MaineCare", mac: "National Government Services", jurisdiction: "JK", payers: ["Anthem Blue Cross Blue Shield", "Harvard Pilgrim Health Care", "Community Health Options"], metros: ["Portland", "Lewiston", "Bangor"], expansion: true, medicaidModel: "fee-for-service", note: "MaineCare is administered predominantly fee-for-service, and Maine's rural provider distribution makes critical access and telehealth billing rules central." },
  { slug: "maryland", name: "Maryland", abbr: "MD", medicaid: "Maryland HealthChoice", mac: "Novitas Solutions", jurisdiction: "JL", payers: ["CareFirst BlueCross BlueShield", "Kaiser Permanente", "Priority Partners"], metros: ["Baltimore", "Columbia", "Silver Spring", "Rockville"], expansion: true, medicaidModel: "managed-care", note: "Maryland's all-payer hospital rate-setting model is unique in the United States and changes facility reimbursement mechanics that exist nowhere else." },
  { slug: "massachusetts", name: "Massachusetts", abbr: "MA", medicaid: "MassHealth", mac: "National Government Services", jurisdiction: "JK", payers: ["Blue Cross Blue Shield of Massachusetts", "Harvard Pilgrim Health Care", "Tufts Health Plan", "Mass General Brigham Health Plan"], metros: ["Boston", "Worcester", "Springfield", "Cambridge"], expansion: true, medicaidModel: "managed-care", note: "MassHealth ACO arrangements shift meaningful risk to provider organizations, so accurate diagnosis documentation affects revenue beyond fee-for-service billing." },
  { slug: "michigan", name: "Michigan", abbr: "MI", medicaid: "Healthy Michigan Plan", mac: "Wisconsin Physicians Service", jurisdiction: "J8", payers: ["Blue Cross Blue Shield of Michigan", "Priority Health", "Meridian Health Plan"], metros: ["Detroit", "Grand Rapids", "Ann Arbor", "Lansing"], expansion: true, medicaidModel: "managed-care", note: "Blue Cross Blue Shield of Michigan holds an unusually concentrated commercial share, which makes a single payer's policy changes disproportionately consequential." },
  { slug: "minnesota", name: "Minnesota", abbr: "MN", medicaid: "Minnesota Medical Assistance", mac: "National Government Services", jurisdiction: "J6", payers: ["Blue Cross and Blue Shield of Minnesota", "HealthPartners", "Medica", "UCare"], metros: ["Minneapolis", "Saint Paul", "Rochester", "Duluth"], expansion: true, medicaidModel: "managed-care", note: "Minnesota's nonprofit-dominated insurance market and county-based purchasing arrangements produce plan structures that differ from most states." },
  { slug: "mississippi", name: "Mississippi", abbr: "MS", medicaid: "MississippiCAN", mac: "Novitas Solutions", jurisdiction: "JH", payers: ["Blue Cross & Blue Shield of Mississippi", "Magnolia Health", "UnitedHealthcare"], metros: ["Jackson", "Gulfport", "Hattiesburg"], expansion: false, medicaidModel: "managed-care", note: "Mississippi has not expanded Medicaid and has the country's highest rate of rural hospital financial distress, making AR discipline especially consequential." },
  { slug: "missouri", name: "Missouri", abbr: "MO", medicaid: "MO HealthNet", mac: "Wisconsin Physicians Service", jurisdiction: "J5", payers: ["Anthem Blue Cross Blue Shield", "Home State Health", "Cigna"], metros: ["Kansas City", "St. Louis", "Springfield", "Columbia"], expansion: true, medicaidModel: "managed-care", note: "Missouri expanded Medicaid by ballot initiative with retroactive eligibility complications, so coverage verification for newly eligible adults requires particular care." },
  { slug: "montana", name: "Montana", abbr: "MT", medicaid: "Montana Medicaid", mac: "Noridian Healthcare Solutions", jurisdiction: "JF", payers: ["Blue Cross and Blue Shield of Montana", "PacificSource", "Allegiance"], metros: ["Billings", "Missoula", "Bozeman", "Great Falls"], expansion: true, medicaidModel: "fee-for-service", note: "Montana administers Medicaid largely fee-for-service, and its frontier geography makes travel, telehealth and critical access billing rules central to rural practices." },
  { slug: "nebraska", name: "Nebraska", abbr: "NE", medicaid: "Heritage Health", mac: "Wisconsin Physicians Service", jurisdiction: "J5", payers: ["Blue Cross and Blue Shield of Nebraska", "Nebraska Total Care", "Medica"], metros: ["Omaha", "Lincoln", "Bellevue"], expansion: true, medicaidModel: "managed-care", note: "Heritage Health integrates physical, behavioral and pharmacy benefits under single plans, which simplifies routing but concentrates authorization authority." },
  { slug: "nevada", name: "Nevada", abbr: "NV", medicaid: "Nevada Medicaid", mac: "Noridian Healthcare Solutions", jurisdiction: "JE", payers: ["Anthem Blue Cross Blue Shield", "Health Plan of Nevada", "SilverSummit Healthplan"], metros: ["Las Vegas", "Henderson", "Reno"], expansion: true, medicaidModel: "managed-care", note: "Nevada's provider shortage relative to population produces long authorization queues, and Las Vegas commercial contracting differs markedly from the north." },
  { slug: "new-hampshire", name: "New Hampshire", abbr: "NH", medicaid: "NH Medicaid Care Management", mac: "National Government Services", jurisdiction: "JK", payers: ["Anthem Blue Cross Blue Shield", "Harvard Pilgrim Health Care", "AmeriHealth Caritas"], metros: ["Manchester", "Nashua", "Concord"], expansion: true, medicaidModel: "managed-care", note: "New Hampshire's small market and proximity to Massachusetts mean many practices hold contracts with Boston-area systems and payers alongside in-state plans." },
  { slug: "new-jersey", name: "New Jersey", abbr: "NJ", medicaid: "NJ FamilyCare", mac: "Novitas Solutions", jurisdiction: "JL", payers: ["Horizon Blue Cross Blue Shield of New Jersey", "AmeriHealth", "Aetna"], metros: ["Newark", "Jersey City", "Paterson", "Trenton"], expansion: true, medicaidModel: "managed-care", note: "Horizon's dominant share plus dense proximity to New York and Philadelphia markets means many New Jersey practices bill across three states' payer landscapes." },
  { slug: "new-mexico", name: "New Mexico", abbr: "NM", medicaid: "Turquoise Care", mac: "Novitas Solutions", jurisdiction: "JH", payers: ["Blue Cross and Blue Shield of New Mexico", "Presbyterian Health Plan", "Western Sky Community Care"], metros: ["Albuquerque", "Las Cruces", "Santa Fe"], expansion: true, medicaidModel: "managed-care", note: "Turquoise Care replaced Centennial Care with revised plan participation, so payer IDs and authorization pathways changed recently and older billing configurations may be stale." },
  { slug: "new-york", name: "New York", abbr: "NY", medicaid: "New York Medicaid", mac: "National Government Services", jurisdiction: "JK", payers: ["Empire BlueCross BlueShield", "Excellus BlueCross BlueShield", "EmblemHealth", "Healthfirst", "Fidelis Care"], metros: ["New York City", "Buffalo", "Rochester", "Albany", "Syracuse"], expansion: true, medicaidModel: "managed-care", note: "New York's eMedNY system, multiple independent regional Blues plans and large Medicaid managed care market make it one of the most fragmented payer environments in the country." },
  { slug: "north-carolina", name: "North Carolina", abbr: "NC", medicaid: "NC Medicaid Managed Care", mac: "Palmetto GBA", jurisdiction: "JM", payers: ["Blue Cross and Blue Shield of North Carolina", "UnitedHealthcare", "WellCare"], metros: ["Charlotte", "Raleigh", "Greensboro", "Durham"], expansion: true, medicaidModel: "managed-care", note: "North Carolina transitioned from fee-for-service to managed care relatively recently, and practices with older billing setups sometimes still route claims incorrectly." },
  { slug: "north-dakota", name: "North Dakota", abbr: "ND", medicaid: "North Dakota Medicaid", mac: "Noridian Healthcare Solutions", jurisdiction: "JF", payers: ["Blue Cross Blue Shield of North Dakota", "Sanford Health Plan", "Medica"], metros: ["Fargo", "Bismarck", "Grand Forks"], expansion: true, medicaidModel: "mixed", note: "North Dakota keeps most Medicaid fee-for-service with a single plan covering the expansion population, so routing depends on which eligibility category the patient falls under." },
  { slug: "ohio", name: "Ohio", abbr: "OH", medicaid: "Ohio Medicaid", mac: "CGS Administrators", jurisdiction: "J15", payers: ["Anthem Blue Cross Blue Shield", "Medical Mutual of Ohio", "CareSource"], metros: ["Columbus", "Cleveland", "Cincinnati", "Toledo"], expansion: true, medicaidModel: "managed-care", note: "Ohio's Medicaid redesign introduced a single pharmacy benefit manager and centralized credentialing, changing enrollment workflows for all participating plans." },
  { slug: "oklahoma", name: "Oklahoma", abbr: "OK", medicaid: "SoonerCare", mac: "Novitas Solutions", jurisdiction: "JH", payers: ["Blue Cross and Blue Shield of Oklahoma", "CommunityCare", "GlobalHealth"], metros: ["Oklahoma City", "Tulsa", "Norman"], expansion: true, medicaidModel: "mixed", note: "Oklahoma moved to SoonerSelect managed care recently after operating fee-for-service for decades, so plan-level rules are new territory for many practices." },
  { slug: "oregon", name: "Oregon", abbr: "OR", medicaid: "Oregon Health Plan", mac: "Noridian Healthcare Solutions", jurisdiction: "JF", payers: ["Regence BlueCross BlueShield of Oregon", "Providence Health Plan", "Moda Health", "PacificSource"], metros: ["Portland", "Eugene", "Salem", "Bend"], expansion: true, medicaidModel: "managed-care", note: "Oregon's Coordinated Care Organizations hold global budgets covering physical, behavioral and dental care, which is structurally unlike conventional Medicaid managed care." },
  { slug: "pennsylvania", name: "Pennsylvania", abbr: "PA", medicaid: "HealthChoices", mac: "Novitas Solutions", jurisdiction: "JL", payers: ["Highmark Blue Cross Blue Shield", "Independence Blue Cross", "UPMC Health Plan", "Geisinger Health Plan"], metros: ["Philadelphia", "Pittsburgh", "Allentown", "Harrisburg"], expansion: true, medicaidModel: "managed-care", note: "Pennsylvania is effectively two commercial markets — Highmark in the west, Independence Blue Cross in the east — with HealthChoices Medicaid zones layered on top." },
  { slug: "rhode-island", name: "Rhode Island", abbr: "RI", medicaid: "RIte Care", mac: "National Government Services", jurisdiction: "JK", payers: ["Blue Cross & Blue Shield of Rhode Island", "Neighborhood Health Plan of RI", "UnitedHealthcare"], metros: ["Providence", "Warwick", "Cranston"], expansion: true, medicaidModel: "managed-care", note: "Rhode Island's small size and single dominant Blues plan mean commercial contracting terms move slowly but affect nearly every practice at once." },
  { slug: "south-carolina", name: "South Carolina", abbr: "SC", medicaid: "Healthy Connections", mac: "Palmetto GBA", jurisdiction: "JM", payers: ["BlueCross BlueShield of South Carolina", "Select Health of South Carolina", "Absolute Total Care"], metros: ["Charleston", "Columbia", "Greenville"], expansion: false, medicaidModel: "managed-care", note: "South Carolina has not expanded Medicaid, and BlueCross BlueShield of South Carolina holds a commanding commercial share plus the Medicare contractor relationship." },
  { slug: "south-dakota", name: "South Dakota", abbr: "SD", medicaid: "South Dakota Medicaid", mac: "Noridian Healthcare Solutions", jurisdiction: "JF", payers: ["Wellmark Blue Cross and Blue Shield", "Sanford Health Plan", "Avera Health Plans"], metros: ["Sioux Falls", "Rapid City", "Aberdeen"], expansion: true, medicaidModel: "fee-for-service", note: "South Dakota administers Medicaid fee-for-service, and its provider market is dominated by two large integrated health systems that also operate health plans." },
  { slug: "tennessee", name: "Tennessee", abbr: "TN", medicaid: "TennCare", mac: "Palmetto GBA", jurisdiction: "JJ", payers: ["BlueCross BlueShield of Tennessee", "Amerigroup", "UnitedHealthcare Community Plan"], metros: ["Nashville", "Memphis", "Knoxville", "Chattanooga"], expansion: false, medicaidModel: "managed-care", note: "TennCare operates under a longstanding federal waiver with a block-grant style financing arrangement found in no other state, and Tennessee has not expanded eligibility." },
  { slug: "texas", name: "Texas", abbr: "TX", medicaid: "Texas Medicaid and STAR", mac: "Novitas Solutions", jurisdiction: "JH", payers: ["Blue Cross and Blue Shield of Texas", "Superior HealthPlan", "Community Health Choice", "Baylor Scott & White Health Plan"], metros: ["Houston", "Dallas", "San Antonio", "Austin", "Fort Worth"], expansion: false, medicaidModel: "managed-care", note: "Texas splits Medicaid across STAR, STAR+PLUS and STAR Kids programs with different plan lineups by service area, and has not expanded eligibility — producing both program complexity and high self-pay volume." },
  { slug: "utah", name: "Utah", abbr: "UT", medicaid: "Utah Medicaid", mac: "Noridian Healthcare Solutions", jurisdiction: "JF", payers: ["Regence BlueCross BlueShield of Utah", "SelectHealth", "University of Utah Health Plans"], metros: ["Salt Lake City", "Provo", "West Valley City", "Ogden"], expansion: true, medicaidModel: "managed-care", note: "Utah's partial expansion history and Intermountain's integrated payer-provider position make commercial contracting unusually concentrated." },
  { slug: "vermont", name: "Vermont", abbr: "VT", medicaid: "Green Mountain Care", mac: "National Government Services", jurisdiction: "JK", payers: ["Blue Cross and Blue Shield of Vermont", "MVP Health Care", "The Vermont Health Plan"], metros: ["Burlington", "Rutland", "Montpelier"], expansion: true, medicaidModel: "fee-for-service", note: "Vermont operates its Medicaid program as its own public managed care entity rather than contracting with commercial MCOs, and its all-payer ACO model shifts risk to providers." },
  { slug: "virginia", name: "Virginia", abbr: "VA", medicaid: "Cardinal Care", mac: "Palmetto GBA", jurisdiction: "JM", payers: ["Anthem HealthKeepers", "Sentara Health Plans", "Aetna Better Health of Virginia"], metros: ["Virginia Beach", "Richmond", "Arlington", "Norfolk"], expansion: true, medicaidModel: "managed-care", note: "Cardinal Care consolidated Virginia's previously separate Medicaid programs under one brand, and Northern Virginia practices frequently bill DC and Maryland payers as well." },
  { slug: "washington", name: "Washington", abbr: "WA", medicaid: "Apple Health", mac: "Noridian Healthcare Solutions", jurisdiction: "JF", payers: ["Premera Blue Cross", "Regence BlueShield", "Kaiser Permanente Washington", "Molina Healthcare"], metros: ["Seattle", "Spokane", "Tacoma", "Vancouver"], expansion: true, medicaidModel: "managed-care", note: "Apple Health integrates physical and behavioral health under single managed care contracts statewide, and Washington's balance billing protections are among the more prescriptive." },
  { slug: "west-virginia", name: "West Virginia", abbr: "WV", medicaid: "Mountain Health Trust", mac: "Palmetto GBA", jurisdiction: "JM", payers: ["Highmark Blue Cross Blue Shield West Virginia", "The Health Plan", "Aetna Better Health"], metros: ["Charleston", "Huntington", "Morgantown"], expansion: true, medicaidModel: "managed-care", note: "West Virginia's rural provider distribution and high chronic disease burden make chronic care management and remote monitoring billing particularly relevant." },
  { slug: "wisconsin", name: "Wisconsin", abbr: "WI", medicaid: "BadgerCare Plus", mac: "National Government Services", jurisdiction: "J6", payers: ["Anthem Blue Cross Blue Shield", "Quartz", "Security Health Plan", "Dean Health Plan"], metros: ["Milwaukee", "Madison", "Green Bay", "Kenosha"], expansion: false, medicaidModel: "managed-care", note: "Wisconsin has not formally expanded Medicaid but covers adults to the poverty line through BadgerCare Plus, producing an eligibility structure unlike either expansion or non-expansion states." },
  { slug: "wyoming", name: "Wyoming", abbr: "WY", medicaid: "Wyoming Medicaid", mac: "Noridian Healthcare Solutions", jurisdiction: "JF", payers: ["Blue Cross Blue Shield of Wyoming", "Cigna", "UnitedHealthcare"], metros: ["Cheyenne", "Casper", "Laramie"], expansion: false, medicaidModel: "fee-for-service", note: "Wyoming administers Medicaid fee-for-service, has not expanded eligibility, and its frontier geography makes it one of the most challenging states for provider network adequacy." },
];

export const stateMap = new Map(states.map((s) => [s.slug, s]));
export const getState = (slug: string) => stateMap.get(slug);
export const stateSlugs = states.map((s) => s.slug);

/**
 * Census regions.
 *
 * Kept as a lookup rather than a field on each state so the 50 entries above
 * stay focused on billing-relevant facts. Regions exist for one reason:
 * grouping 50 state links into four navigable blocks, which is the difference
 * between an internal linking structure and an undifferentiated wall.
 */
export type Region = "Northeast" | "Midwest" | "South" | "West";

const REGION_BY_ABBR: Record<string, Region> = {
  CT: "Northeast", ME: "Northeast", MA: "Northeast", NH: "Northeast", RI: "Northeast",
  VT: "Northeast", NJ: "Northeast", NY: "Northeast", PA: "Northeast",

  IL: "Midwest", IN: "Midwest", MI: "Midwest", OH: "Midwest", WI: "Midwest",
  IA: "Midwest", KS: "Midwest", MN: "Midwest", MO: "Midwest", NE: "Midwest",
  ND: "Midwest", SD: "Midwest",

  DE: "South", FL: "South", GA: "South", MD: "South", NC: "South", SC: "South",
  VA: "South", DC: "South", WV: "South", AL: "South", KY: "South", MS: "South",
  TN: "South", AR: "South", LA: "South", OK: "South", TX: "South",

  AZ: "West", CO: "West", ID: "West", MT: "West", NV: "West", NM: "West",
  UT: "West", WY: "West", AK: "West", CA: "West", HI: "West", OR: "West", WA: "West",
};

export const regionOf = (abbr: string): Region => REGION_BY_ABBR[abbr] ?? "West";

export const REGIONS: Region[] = ["Northeast", "Midwest", "South", "West"];

export const statesByRegion = (): Record<Region, StateInfo[]> => {
  const out = { Northeast: [], Midwest: [], South: [], West: [] } as Record<Region, StateInfo[]>;
  for (const s of states) out[regionOf(s.abbr)].push(s);
  return out;
};

/** Neighbouring-market links: other states in the same region, for cross-linking. */
export const nearbyStates = (slug: string, limit = 6) => {
  const self = states.find((s) => s.slug === slug);
  if (!self) return [];
  const region = regionOf(self.abbr);
  return states.filter((s) => s.slug !== slug && regionOf(s.abbr) === region).slice(0, limit);
};
